/*
 * Work — Signal Chain UI harness.
 *
 * This file existed with NO test coverage while three of the four bugs Tim hit
 * on hardware lived in it: a machine select that could not reach the last
 * machine, a knob response that only produced end stops, and a refresh that
 * stalled the UI for the better part of a second per detent. The engine had
 * 445 checks and every one of them passed through all three, because they are
 * not engine bugs — they are "does the surface behave like an instrument"
 * bugs. Hence this harness.
 *
 * As with test/ui_overtake.mjs, the mock's answers come from
 * build/contract.json, generated by test/dump_contract.c FROM THE ENGINE. A
 * mock written from the UI's assumptions encodes the same misunderstanding
 * twice and stays green while the module is dead on the Move.
 *
 * The cost model is mocked too, and it is the point of half these checks: in a
 * chain editor schwung shims host_module_get_param onto shadow_get_param,
 * which busy-waits for the shim and is serviced once per SPI frame (~23 ms),
 * giving up after 100 ms. Round-trips are counted, not just correctness.
 *
 * Run via `make test`.
 */
import fs from 'fs';
import vm from 'vm';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const contract = JSON.parse(fs.readFileSync(path.join(root, 'build/contract.json'), 'utf8'));
const settable = new Set([...contract.settable, ...contract.commands]);
const MACHINES = contract.get.machines.split(',');

let checks = 0;
let failures = 0;
function check(cond, msg) {
    checks++;
    if (!cond) { failures++; console.log(`  FAIL  ${msg}`); }
}

/* ------------------------------------------------------------- the mock */

const SCREEN_W = 128;
const SCREEN_H = 64;

/* The Move's font is a proportional bitmap; 6 px per character is an
 * approximation of it, deliberately no narrower than the real thing. The UI
 * fits text with the host's own text_width() rather than a character count, so
 * it stays inside its boxes whatever the true metrics are — this mock only has
 * to be wide enough that a layout which overflows here would overflow there. */
const CHAR_W = 6;

function makeHost() {
    const store = Object.assign({}, contract.get);
    const writes = [];
    const reads = [];
    const roundTrips = [];
    const unknownReads = new Set();
    const unknownWrites = new Set();
    const screen = [];
    let failNextReads = 0;

    const host = {
        host_module_get_param(key) {
            roundTrips.push(key);
            reads.push(key);
            /* A timed-out round-trip returns null. It is NOT zero, and the UI
             * must not treat it as one — that is what used to snap the slot
             * back to Bypass under load. */
            if (failNextReads > 0) { failNextReads--; return null; }
            if (key in store) return store[key];
            unknownReads.add(key);
            return null;
        },
        host_module_set_param(key, val) {
            writes.push({ key, val });
            const fam = key.replace(/\d+/g, '#');
            const known = settable.has(key)
                || [...settable].some((s) => s.replace(/\d+/g, '#') === fam);
            if (!known) unknownWrites.add(key);
            store[key] = `${val}`;
        },
        clear_screen() { screen.length = 0; },
        print(x, y, text) { screen.push({ x, y, text: `${text}` }); },
        fill_rect() {},
        draw_rect() {},
        text_width(t) { return `${t}`.length * CHAR_W; },
        Math, Number, JSON, String, Array, parseInt, parseFloat, isFinite, console
    };
    host.globalThis = host;

    return {
        host, store, writes, reads, roundTrips, unknownReads, unknownWrites, screen,
        failReads(n) { failNextReads = n; }
    };
}

/* The three schwung shared modules the UI imports. decodeDelta is transcribed
 * from schwung's src/shared/input_filter.mjs — the ACCUMULATED-count contract
 * is the whole reason the knob maths needed fixing, so it must not be
 * simplified here. */
const STUBS = {
    '/data/UserData/schwung/shared/constants.mjs': `
        export const MoveKnob1 = 71, MoveShift = 49, MoveMainButton = 3, MoveMainKnob = 14;
    `,
    '/data/UserData/schwung/shared/input_filter.mjs': `
        export function decodeDelta(v){ if(v===0) return 0; if(v>=1&&v<=63) return v; if(v>=65&&v<=127) return -(128-v); return 0; }
        /* Transcribed from schwung's src/shared/input_filter.mjs: clock,
         * sysex, aftertouch and the capacitive knob-touch notes. */
        export function shouldFilterMessage(d){
            const st = d[0], t = st & 0xF0;
            if (st === 0xF8 || st === 0xF0 || st === 0xF7) return true;
            if (t === 0xD0 || t === 0xA0) return true;
            if ((t === 0x90 || t === 0x80) && d[1] < 10) return true;
            return false;
        }
    `,
    '/data/UserData/schwung/shared/screen_reader.mjs': `
        export function announce(){}
        export function announceParameter(){}
        export function announceView(){}
    `
};

async function loadUI(seed) {
    const ctx = makeHost();
    if (seed) Object.assign(ctx.store, seed);
    const context = vm.createContext(ctx.host);
    const src = fs.readFileSync(path.join(root, 'src/ui_chain.js'), 'utf8');

    const mod = new vm.SourceTextModule(src, { context, identifier: 'ui_chain.js' });
    await mod.link(async (spec) => {
        const code = STUBS[spec];
        if (!code) throw new Error(`unexpected import: ${spec}`);
        const m = new vm.SourceTextModule(code, { context, identifier: spec });
        await m.link(() => { throw new Error('nested import'); });
        return m;
    });
    await mod.evaluate();
    return ctx;
}

const cc = (num, val) => [0xB0, num, val];
const KNOB1 = 71, JOG = 14;

/* Run enough ticks for the background refresh to settle. */
function settle(ctx, n) {
    for (let i = 0; i < (n || 40); i++) ctx.host.tick();
}

/* --------------------------------------------------------------- tests */

async function testInitIsCheapAndHonest() {
    console.log('init costs a handful of round-trips and reads only served keys');
    const ctx = await loadUI();
    ctx.host.init();

    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
    check(ctx.roundTrips.length <= 6,
          `init cost ${ctx.roundTrips.length} blocking round-trips — at ~23 ms each ` +
          `that is a visible stall before the first frame`);
    check(ctx.reads.includes('machines'), 'UI never asked the engine for the machine list');
    check(ctx.screen.length > 0, 'init drew nothing');
}

/* The rule that fixes "I can change fx but it's super slow": the knob handler
 * does no reading at all. Reading the slot back after a machine change cost
 * ~36 round-trips, close to a second of busy-wait, per detent. */
async function testKnobHandlerNeverReads() {
    console.log('turning a knob performs no blocking reads');
    const ctx = await loadUI();
    ctx.host.init();
    settle(ctx);

    ctx.roundTrips.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));         /* machine 1 */
    check(ctx.roundTrips.length === 0,
          `a knob detent cost ${ctx.roundTrips.length} round-trips (${ctx.roundTrips.join(', ')})`);

    ctx.roundTrips.length = 0;
    for (let i = 0; i < 10; i++) ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    check(ctx.roundTrips.length === 0,
          `scrolling the machine list cost ${ctx.roundTrips.length} round-trips`);
}

/* The steady state must not saturate the param channel either. Every read
 * claims an SPI frame; when this UI polled continuously, OTHER reads timed out
 * and came back empty. */
async function testSteadyStateIsQuiet() {
    console.log('the idle refresh does not saturate the param channel');
    const ctx = await loadUI();
    ctx.host.init();
    settle(ctx, 100);                       /* let the burst finish */

    ctx.roundTrips.length = 0;
    for (let i = 0; i < 44; i++) ctx.host.tick();     /* one second */
    check(ctx.roundTrips.length <= 8,
          `${ctx.roundTrips.length} reads per second at idle — one read costs a whole ` +
          `SPI frame, so this is what starves everything else`);
}

async function testPageFillsInPromptly() {
    console.log('an unread page fills in within a few hundred ms');
    const ctx = await loadUI();
    ctx.host.init();
    settle(ctx, 60);

    ctx.host.onMidiMessageInternal(cc(JOG, 1));      /* to FX 1 */
    for (let i = 0; i < 20; i++) ctx.host.tick();    /* ~450 ms */

    const blanks = ctx.screen.filter((s) => s.text === '--').length;
    check(blanks === 0, `${blanks} knob values still read "--" after ~450 ms`);
}

/* Knob response has been wrong in both directions on hardware, so pin the
 * numbers. One detent moves one; a fast spin moves a quarter of the range. */
async function testKnobResponseCurve() {
    console.log('knob response: one detent moves one, a fast spin moves a quarter of the range');
    const cap = Math.ceil((MACHINES.length - 1) / 4);

    let ctx = await loadUI({ machine1: '5' });
    ctx.host.init();
    settle(ctx);
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    let w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 6,
          `one detent moved machine1 to ${w && w.val} — expected 6`);

    ctx = await loadUI({ machine1: '5' });
    ctx.host.init();
    settle(ctx);
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 25));
    w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 5 + cap,
          `a 25-detent event moved machine1 to ${w && w.val} — expected ${5 + cap}`);

    /* Four flicks must cross the entire list. This is the "super slow"
     * regression: one-step-per-event needed twenty. */
    ctx = await loadUI({ machine1: '0' });
    ctx.host.init();
    settle(ctx);
    for (let i = 0; i < 4; i++) ctx.host.onMidiMessageInternal(cc(KNOB1, 63));
    const last = ctx.writes.filter((x) => x.key === 'machine1').pop();
    check(last && parseInt(`${last.val}`, 10) === MACHINES.length - 1,
          `four full flicks reached machine ${last && last.val} of ${MACHINES.length - 1}`);
}

/* The machine select's bound must come from the engine's own list. A constant
 * here is what left Granulator — the 21st machine — unreachable. */
async function testMachineRangeFollowsTheEngine() {
    console.log('every machine the engine lists is reachable');
    const ctx = await loadUI({ machine1: `${MACHINES.length - 2}` });
    ctx.host.init();
    settle(ctx);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 40));
    const w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === MACHINES.length - 1,
          `could not reach "${MACHINES[MACHINES.length - 1]}" (index ${MACHINES.length - 1}); ` +
          `got ${w && w.val}`);

    /* and it must not run off the end into a machine that does not exist */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 40));
    const over = ctx.writes.find((x) => x.key === 'machine1');
    check(!over, `machine1 was pushed past the end of the list to ${over && over.val}`);
}

/* A read that times out returns null. Collapsing that into 0 meant the mirror
 * silently became Bypass, and the next knob turn WROTE that back to the DSP. */
async function testFailedReadNeverBecomesZero() {
    console.log('a failed read leaves the mirror alone instead of writing Bypass');
    const ctx = await loadUI({ machine1: '13' });
    ctx.host.init();
    settle(ctx);

    ctx.failReads(200);                     /* the channel goes dark */
    settle(ctx, 60);
    ctx.failReads(0);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    const w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 14,
          `after a dead param channel the UI wrote machine1=${w && w.val}; it must ` +
          `continue from 13, not from a zeroed mirror`);

    const zeroed = ctx.writes.find((x) => x.key === 'machine1' && `${x.val}` === '0');
    check(!zeroed, 'a failed read produced a write of 0 — that is the snap-to-Bypass bug');
}

/* Nothing may be written from a value the UI has never actually read. */
async function testNoWriteBeforeFirstRead() {
    console.log('a knob turned before its value is known writes nothing');
    const ctx = await loadUI();
    ctx.host.init();
    /* deliberately do NOT settle — the FX pages are still unread */
    ctx.host.onMidiMessageInternal(cc(JOG, 1));      /* to FX 1 */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 5));
    check(ctx.writes.length === 0,
          `wrote ${JSON.stringify(ctx.writes)} from a parameter it had not read yet`);
}

/* "the text is scrunched": four 32 px columns printed with a fixed six-
 * character slice, and a header whose right-hand machine name ran straight
 * through the page title. */
function layoutProblems(screen) {
    const problems = [];
    for (const s of screen) {
        const w = `${s.text}`.length * CHAR_W;
        if (s.x + w > SCREEN_W) problems.push(`"${s.text}" runs to x=${s.x + w} (>${SCREEN_W})`);
        if (s.y < 0 || s.y > SCREEN_H - 7) problems.push(`"${s.text}" at y=${s.y} is off-screen`);
    }
    /* overlap: two strings drawn on the same baseline must not collide */
    const rows = new Map();
    for (const s of screen) {
        if (!rows.has(s.y)) rows.set(s.y, []);
        rows.get(s.y).push(s);
    }
    for (const [y, items] of rows) {
        items.sort((a, b) => a.x - b.x);
        for (let i = 1; i < items.length; i++) {
            const prevEnd = items[i - 1].x + `${items[i - 1].text}`.length * CHAR_W;
            if (prevEnd > items[i].x) {
                problems.push(`"${items[i - 1].text}" and "${items[i].text}" overlap at y=${y}`);
            }
        }
    }
    return problems;
}

async function testLayoutNeverCollides() {
    console.log('no drawn text overflows the screen or its neighbour');
    /* The widest machine names in the engine, in both slots at once. */
    const widest = MACHINES.reduce((a, b) => (b.length > a.length ? b : a));
    const idx = MACHINES.indexOf(widest);
    const ctx = await loadUI({ machine1: `${idx}`, machine2: `${idx}` });
    ctx.host.init();
    settle(ctx, 80);

    for (let p = 0; p < 5; p++) {
        settle(ctx, 30);
        const problems = layoutProblems(ctx.screen);
        check(problems.length === 0,
              `page ${p} layout: ${problems.join('; ')}`);
        ctx.host.onMidiMessageInternal(cc(JOG, 1));
    }
}

/* The machines page is where the name has to be legible — it used to be cut to
 * six characters, so every reverb read "Rumskl". */
async function testMachineNamesAreNotTruncatedToSixChars() {
    console.log('the machines page shows a readable machine name');
    /* Take the LONGEST name the engine reports rather than naming one here.
     * This test used to hardcode a prefix of the machine it wanted, so it
     * failed the moment the machine was renamed — and a test that breaks on a
     * rename is testing the name, not the truncation it exists to catch. */
    const longest = MACHINES.reduce((a, b) => (b.length > a.length ? b : a), '');
    const idx = MACHINES.indexOf(longest);
    check(longest.length > 12,
          `no machine name is long enough to catch truncation (longest is ` +
          `"${longest}") — this test can no longer fail`);

    const ctx = await loadUI({ machine1: `${idx}` });
    ctx.host.init();
    settle(ctx, 80);

    const shown = ctx.screen.map((s) => s.text);
    const name = shown.find((t) => longest.startsWith(t.slice(0, 8)) && t.length > 4);
    check(!!name, `no machine name on screen; got ${JSON.stringify(shown)}`);
    check(name === longest,
          `machine name was cut to "${name}", expected "${longest}" — the old ` +
          `six-character slice made every long name unreadable`);
}

/* Changing a machine reloads that slot's defaults in the DSP, so the knob
 * labels and the eight values are stale. They must refresh — just not from
 * inside the knob handler. */
async function testMachineChangeRefreshesLabels() {
    console.log('a machine change refreshes that slot\'s labels, off the input path');
    const ctx = await loadUI({ machine1: '0' });
    ctx.host.init();
    settle(ctx, 80);

    const target = MACHINES.indexOf('Flutter');
    ctx.store.machine1 = `${target}`;
    ctx.store.labels1 = contract.get.labels1;

    ctx.reads.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    check(ctx.reads.length === 0, 'the knob handler read the DSP');

    settle(ctx, 40);
    check(ctx.reads.includes('labels1'),
          'the knob labels for the changed slot were never refreshed');
}

async function testEveryWrittenKeyIsAccepted() {
    console.log('every key the UI writes is one the engine accepts');
    const ctx = await loadUI();
    ctx.host.init();
    settle(ctx, 60);

    for (let p = 0; p < 5; p++) {
        /* Settle BEFORE turning anything: a knob whose value has not been read
         * yet deliberately writes nothing, so turning first made this whole
         * check vacuous — it passed while exercising two keys out of thirty. */
        settle(ctx, 40);
        for (let k = 0; k < 8; k++) {
            ctx.host.onMidiMessageInternal(cc(KNOB1 + k, 3));
            ctx.host.onMidiMessageInternal(cc(KNOB1 + k, 125));
        }
        ctx.host.onMidiMessageInternal(cc(JOG, 1));
    }

    const distinct = new Set(ctx.writes.map((w) => w.key));
    check(distinct.size >= 25,
          `only ${distinct.size} distinct keys were exercised (${[...distinct].join(', ')}) — ` +
          `this check is meant to cover every knob on every page`);
    check(ctx.unknownWrites.size === 0,
          `UI wrote keys the engine does not accept: ${[...ctx.unknownWrites].join(', ')}`);
    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
}


/* The same garbage that flooded the overtake build reaches the chain UI too —
 * it is the same MIDI_IN ring. Captured from the device 2026-07-29. */
async function testGarbageMidiIsIgnored() {
    console.log('sysex, clock and misaligned bytes never reach the surface');
    const ctx = await loadUI();
    ctx.host.init();
    settle(ctx, 40);
    ctx.writes.length = 0;

    const garbage = [
        [178, 0, 77], [240, 0, 33], [29, 1, 1], [58, 0, 77], [0, 247, 0],
        [0xF8, 0, 0], [0xD0, 64, 0], [0xA0, 60, 100], [0x90, 3, 100]
    ];
    for (let i = 0; i < 200; i++) {
        for (const g of garbage) ctx.host.onMidiMessageInternal(g);
        ctx.host.onMidiMessageInternal([0, 0, 0]);
    }
    check(ctx.writes.length === 0,
          `garbage MIDI wrote ${ctx.writes.length} parameters: ` +
          JSON.stringify(ctx.writes.slice(0, 4)));

    /* and real input still gets through */
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    check(ctx.writes.length > 0, 'the filter swallowed a real knob turn');
}

/* ---------------------------------------------------------------- runner */

const TESTS = [
    testInitIsCheapAndHonest,
    testGarbageMidiIsIgnored,
    testKnobHandlerNeverReads,
    testSteadyStateIsQuiet,
    testPageFillsInPromptly,
    testKnobResponseCurve,
    testMachineRangeFollowsTheEngine,
    testFailedReadNeverBecomesZero,
    testNoWriteBeforeFirstRead,
    testLayoutNeverCollides,
    testMachineNamesAreNotTruncatedToSixChars,
    testMachineChangeRefreshesLabels,
    testEveryWrittenKeyIsAccepted
];

console.log('Work chain UI harness (mocked against the real engine contract)\n');
for (const t of TESTS) await t();
console.log(`\n${checks} checks, ${failures} failed`);
process.exit(failures ? 1 : 0);
