/*
 * Overwork — UI harness.
 *
 * Loads src/ui_overtake.js in a sandbox with the host globals mocked, drives
 * real input sequences, and checks what the UI does with them.
 *
 * The mock's get_param answers come from build/contract.json, generated by
 * test/dump_contract.c FROM THE ENGINE ITSELF. That matters: a mock written
 * from the UI's assumptions encodes the same misunderstanding twice and stays
 * green while the feature is broken on hardware — which is exactly how Mono
 * shipped a preset browser that never listed a file. The harness also fails if
 * the UI reads a key the engine does not serve, or writes one it does not
 * accept, so contract drift is caught rather than silently tolerated.
 *
 * Run via `make test`.
 */
import fs from 'fs';
import vm from 'vm';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const contract = JSON.parse(fs.readFileSync(path.join(root, 'build/contract.json'), 'utf8'));
const settable = new Set([...contract.settable, ...contract.commands]);

/* Where MIX sits on the GLOBAL page. Derived rather than written down, because
 * the page grew a third select and every hardcoded index after it shifted. */
const N_STAGES = (contract.get.effm || '0,0').split(',').length - 1;
const MIX_KNOB = N_STAGES;

/* Which machines each stage accepts, taken from the ENGINE's answer rather
 * than restated here. A second copy of this table is a copy that drifts, and
 * these tests exist precisely to catch the UI's copy drifting from it. */
const codes = (t) => (t || '').split(',').map(Number).filter(Number.isFinite);
const SRC_FAMILY = codes(contract.get.src_codes);
const FX_FAMILY  = codes(contract.get.fx_codes);
/* The key each stage's machine select answers to, stage-indexed. */
const STAGE_KEY  = ['src', 'fx1', 'fx2'];

/* Palette pads in reading order, minus undo/memo/song — the same order the UI
 * builds from PALETTE_PADS. Position N here holds family member N. */
const PALETTE_ORDER = [92, 93, 94, 95, 96, 97, 98, 99,
                       84, 85, 86, 87, 88, 89, 90, 91,
                       76, 77, 78, 79, 80];

let checks = 0;
let failures = 0;
function check(cond, msg) {
    checks++;
    if (!cond) { failures++; console.log(`  FAIL  ${msg}`); }
}

/* ------------------------------------------------------------- the mock */

/* Keys the engine serves as families — the fixture holds concrete instances,
 * so a request for lock12_3 is legal if lock<N>_<P> is a served family. */
const FAMILIES = [
    /^step\d+$/, /^locks\d+$/, /^lock\d+_\d+$/, /^locklabel\d+$/, /^prob\d+$/, /^trigtype\d+$/, /^song_row\d+$/
];

function familyServed(key) {
    if (!FAMILIES.some((re) => re.test(key))) return false;
    /* the family is served if the fixture holds at least one of its members */
    const shape = key.replace(/\d+/g, '#');
    return Object.keys(contract.get).some((k) => k.replace(/\d+/g, '#') === shape);
}

/* A virtual filesystem implementing QuickJS's REAL contracts, copied from
 * schwung's own preset browser and the C source — never from the code under
 * test. The two that bite:
 *   os.readdir  -> [names, errno] TUPLE, and names includes "." and ".."
 *   os.rename / os.remove -> return 0 or -errno, and NEVER throw
 * Host file bindings are separate and DO return booleans. */
function makeVFS() {
    const files = new Map();
    const binaries = new Map();     /* path -> Uint8Array, for base64 reads */
    const dirs = new Set();
    let renameFails = false;

    return {
        files, dirs, binaries,
        failRenames(v) { renameFails = v; },

        readdir(path) {
            /* A file is not a directory: the real os.readdir answers ENOTDIR,
             * which is how the recursive sample scan terminates. Answering
             * ENOENT instead would hide a walk that never bottoms out. */
            if (files.has(path) || binaries.has(path)) return [[], 20];
            if (!dirs.has(path)) return [[], 2];            /* ENOENT */
            const names = ['.', '..'];                       /* real listings carry these */
            /* Child DIRECTORIES as well as files — without them the mock
             * cannot represent a tree, and a recursive walk has nothing to
             * descend into, which looks exactly like a broken walk. */
            for (const f of [...files.keys(), ...binaries.keys(), ...dirs]) {
                if (f.startsWith(path + '/')) {
                    const rest = f.slice(path.length + 1);
                    if (!rest.includes('/') && !names.includes(rest)) names.push(rest);
                }
            }
            return [names, 0];
        },
        rename(a, b) {
            if (renameFails) return -1;
            if (!files.has(a)) return -2;
            files.set(b, files.get(a));
            files.delete(a);
            return 0;
        },
        remove(p) {
            if (!files.has(p)) return -2;
            files.delete(p);
            return 0;
        },
        mkdir(p) { dirs.add(p); return 0; }
    };
}

function makeHost() {
    const store = Object.assign({}, contract.get);
    const writes = [];
    const reads = [];
    const unknownReads = new Set();
    const unknownWrites = new Set();
    const leds = new Map();
    const screen = [];
    const roundTrips = [];   /* one entry per blocking read of the DSP */
    let shiftState = 0;

    const vfs = makeVFS();

    const host = {
        __vfs: vfs,
        /* Host file bindings return booleans / string-or-null — a DIFFERENT
         * contract from the os.* calls above. */
        host_write_file(path, data) {
            const dir = path.slice(0, path.lastIndexOf('/'));
            if (!vfs.dirs.has(dir)) return false;
            vfs.files.set(path, String(data));
            return true;
        },
        host_read_file(path) {
            return vfs.files.has(path) ? vfs.files.get(path) : null;
        },
        /* Binary-safe read. host_read_file returns a C string and stops at the
         * first NUL, which in a WAV is usually inside the header — that is why
         * the loader uses this one. */
        host_read_file_base64(path) {
            const raw = vfs.binaries.get(path);
            if (!raw) return null;
            return Buffer.from(raw).toString('base64');
        },
        host_ensure_dir(path) { vfs.dirs.add(path); return true; },
        /* The shim is authoritative for SHIFT. Tracking it locally from CC 49
         * latches when a release is missed, and on hardware that made a knob
         * edit the base value instead of writing a lock. */
        shadow_get_shift_held() { return shiftState; },
        host_flush_display() {},

        /* Every one of these is a blocking round-trip on hardware, serviced
         * once per SPI frame. Counting them is the point — a UI that is
         * "correct" but takes sixty frames to redraw is broken on the Move. */
        host_module_get_param(key) {
            roundTrips.push({ bulk: false, keys: [key] });
            reads.push(key);
            /* work_get_param("state") appends the recorded sample path when
             * there is one. Modelling only the PARSE side and not this one is
             * how a save that silently drops the path still passes. */
            if (key === 'state' && store.sample_path) {
                const esc = `${store.sample_path}`.replace(/([\\"])/g, '\\$1');
                return `${store.state}`.replace(/\}\s*$/, `,"smp":"${esc}"}`);
            }
            if (key in store) return store[key];
            if (familyServed(key)) {
                /* a member the fixture did not capture: answer the way the
                 * engine does for an untouched step */
                if (/^lock\d+_\d+$/.test(key)) return '-1';
                if (/^step\d+$/.test(key)) return '0:0:0:0:0';
                if (/^locks\d+$/.test(key)) return '';
                if (/^locklabel\d+$/.test(key)) return '?';
            }
            unknownReads.add(key);
            return null;
        },
        /* BULK_GET, transcribed from shim_handle_param_bulk / bulk_next in
         * schwung's src/schwung_shim.c — NOT from the code under test. The
         * request is "<count>\n" then count records of "<len>\n<key>"; the
         * response is the same shape carrying values, and a key the DSP does
         * not answer comes back as a zero-length record rather than being
         * omitted. The shim refuses more than 64 items outright. */
        host_module_get_params(blob) {
            const s = `${blob}`;
            let p = 0;
            const readLen = () => {
                let n = 0, any = false;
                while (p < s.length && s[p] >= '0' && s[p] <= '9') {
                    n = n * 10 + (s.charCodeAt(p) - 48); p++; any = true;
                }
                if (!any || s[p] !== '\n') return -1;
                p++;
                return n;
            };
            const count = readLen();
            if (count < 0) return null;
            if (count > 64) return null;              /* SHADOW_BULK_MAX_ITEMS */
            const keys = [];
            for (let i = 0; i < count; i++) {
                const len = readLen();
                if (len < 0) return null;
                keys.push(s.slice(p, p + len));
                p += len;
            }
            roundTrips.push({ bulk: true, keys });
            let out = `${keys.length}\n`;
            for (const k of keys) {
                reads.push(k);
                let v = null;
                if (k in store) v = store[k];
                else if (familyServed(k)) {
                    if (/^lock\d+_\d+$/.test(k)) v = '-1';
                    else if (/^step\d+$/.test(k)) v = '0:0:0:0:0';
                    else if (/^locks\d+$/.test(k)) v = '';
                    else if (/^locklabel\d+$/.test(k)) v = '?';
                }
                if (v === null) { unknownReads.add(k); v = ''; }
                out += `${`${v}`.length}\n${v}`;
            }
            return out;
        },
        setShift(v) { shiftState = v ? 1 : 0; },
        host_module_set_param(key, val) {
            writes.push({ key, val });
            /* Model the sample transfer the way work_core.c does, so
             * sample_frames/sample_name read back the way the engine reports
             * them. Without this the mock records the writes and answers the
             * fixture's stale values, and a UI that correctly asks the ENGINE
             * what landed looks broken. */
            if (key === 'sample_begin') {
                const [n, nm] = `${val}`.split(':');
                store.__declared = parseInt(n, 10) || 0;
                store.__pending = nm || '';
                store.__fill = 0;
            } else if (key === 'sample_chunk') {
                const bytes = Buffer.from(`${val}`, 'base64').length;
                store.__fill = (store.__fill || 0) + Math.floor(bytes / 4);
            } else if (key === 'sample_end') {
                const n = Math.min(store.__fill || 0, store.__declared || 0);
                store.sample_frames = `${n}`;
                store.sample_name = n > 0 ? (store.__pending || '') : '';
            } else if (key === 'sample_clear') {
                store.sample_frames = '0';
                store.sample_name = '';
                store.sample_path = '';
            } else if (key === 'state') {
                /* apply_state parses the recorded sample path back out of the
                 * blob. Modelling it here is what lets a preset-load test see
                 * what the engine would actually hand back — without it the
                 * mock answers the fixture's stale path and a UI that
                 * correctly reloads the audio looks like it did nothing. */
                const m = /"smp":"((?:[^"\\]|\\.)*)"/.exec(`${val}`);
                if (m) store.sample_path = m[1].replace(/\\(.)/g, '$1');
            }
            const fam = key.replace(/\d+/g, '#');
            const known = settable.has(key)
                || [...settable].some((s) => s.replace(/\d+/g, '#') === fam);
            if (!known) unknownWrites.add(key);
            store[key] = `${val}`;
        },
        setLED(note, color) { leds.set(note, color); },
        setButtonLED(cc, color) { leds.set(`cc${cc}`, color); },
        clear_screen() { screen.length = 0; },
        print(x, y, text) { screen.push({ x, y, text }); },
        fill_rect() {},
        draw_rect() {},
        text_width(t) { return String(t).length * 5; },
        move_midi_internal_send() {},
        Date,
        Math,
        Number,
        JSON,
        String,
        Array,
        parseInt,
        parseFloat,
        isFinite,
        console
    };
    host.globalThis = host;
    /* What the screen reader was told. Some views draw a status the user sees
     * and others only speak it, so a test that checks the screen alone cannot
     * tell "nothing happened" from "it told you, elsewhere". */
    const spoken = [];
    host.__spoken = spoken;
    return { host, vfs, writes, reads, roundTrips, unknownReads, unknownWrites,
             leds, screen, store, spoken };
}

/* Stub the three schwung shared modules the UI imports. */
const STUBS = {
    '/data/UserData/schwung/shared/constants.mjs': `
        export const MoveKnob1 = 71, MoveShift = 49, MoveMainButton = 3, MoveMainKnob = 14;
        export const Black=0, White=120, LightGrey=118, DarkGrey=124, Red=127, BrightRed=1;
        export const Blue=125, Green=126, BrightGreen=8, Cyan=14, Purple=22, SkyBlue=47;
        export const Lime=31, OrangeRed=2, BurntOrange=28, YellowGreen=30, TealGreen=12, Rose=24;
    `,
    '/data/UserData/schwung/shared/input_filter.mjs': `
        export function decodeDelta(v){ if(v===0) return 0; if(v>=1&&v<=63) return v; if(v>=65&&v<=127) return -(128-v); return 0; }
        export function shouldFilterMessage(d){ const st=d[0], t=st&0xF0;
            if(st===0xF8||st===0xF0||st===0xF7) return true;
            if(t===0xD0||t===0xA0) return true;
            if((t===0x90||t===0x80)&&d[1]<10) return true;
            return false; }
        export function setLED(n,c,f){ globalThis.setLED(n,c,f); }
        export function setButtonLED(n,c,f){ globalThis.setButtonLED(n,c,f); }
    `,
    '/data/UserData/schwung/shared/screen_reader.mjs': `
        export function announce(t){ globalThis.__spoken.push(String(t)); }
        export function announceParameter(t){ globalThis.__spoken.push(String(t)); }
        export function announceView(t){ globalThis.__spoken.push(String(t)); }
    `,
    'os': `
        export function readdir(p){ return globalThis.__vfs.readdir(p); }
        export function rename(a,b){ return globalThis.__vfs.rename(a,b); }
        export function remove(p){ return globalThis.__vfs.remove(p); }
        export function mkdir(p){ return globalThis.__vfs.mkdir(p); }
    `
};

async function loadUI() {
    const ctx = makeHost();
    const context = vm.createContext(ctx.host);
    const src = fs.readFileSync(path.join(root, 'src/ui_overtake.js'), 'utf8');

    const mod = new vm.SourceTextModule(src, { context, identifier: 'ui_overtake.js' });
    await mod.link(async (spec) => {
        const code = STUBS[spec];
        if (!code) throw new Error(`unexpected import: ${spec}`);
        const m = new vm.SourceTextModule(code, { context, identifier: spec });
        await m.link(() => { throw new Error('nested import'); });
        return m;
    });
    await mod.evaluate();
    return ctx;
}

/* MIDI helpers matching what the shim delivers */
const cc   = (num, val) => [0xB0, num, val];
/* Injecting CC 49 alone is no longer enough: the UI asks the shim. Tests that
 * hold Shift must move the shim's view too, which is what the hardware does. */
function holdShift(ctx, on) {
    /* Tick past the post-init settling window first. The UI ignores Shift for
     * about a second after init, because the launch gesture is itself a Shift
     * combo whose release is swallowed while init runs — so a module that
     * trusted the flag started life latched. A real user cannot press Shift in
     * the same millisecond they opened the module; the harness should not
     * either. */
    for (let i = 0; i < 50; i++) ctx.host.tick();
    ctx.host.setShift(on);
    ctx.host.onMidiMessageInternal(cc(49, on ? 127 : 0));
}
/* Move's step buttons are NOTES 16-31, not CCs. The harness sent them as CCs,
 * which is why every step-related check passed while the sequencer could not
 * be played on hardware at all — the mock encoded my assumption instead of the
 * device's contract. Confirmed from the device log: status=144 d1=20 d2=127.
 * schwung's hardware notes: "Pads notes 68-99. Steps notes 16-31." */
const step     = (n, val) => [0x90, 16 + n, val];
const stepDown = (n) => step(n, 127);
const stepUp   = (n) => step(n, 0);
const noteOn  = (n) => [0x90, n, 127];
const noteOff = (n) => [0x80, n, 0];

const KNOB1 = 71, JOG = 14, SHIFT = 49, STEP1 = 16, JOG_CLICK = 3;

/* --------------------------------------------------------------- tests */

async function testInitReadsOnlyServedKeys() {
    console.log('init reads only keys the engine serves');
    const ctx = await loadUI();
    ctx.host.init();
    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
    check(ctx.reads.includes('machines'), 'UI never asked for the machine list');
    check(ctx.reads.includes('labels_src'), 'UI never asked for the SRC stage knob labels');
    check(ctx.reads.includes('src_codes') && ctx.reads.includes('fx_codes'),
          'UI never asked the engine which machines each stage accepts');
    check(ctx.screen.length > 0, 'init drew nothing to the screen');
    check(ctx.leds.size > 20, `init painted only ${ctx.leds.size} LEDs`);
}

/* The headline gesture. Holding a step and turning a knob must write a
 * lock<step>_<param> key — not the base parameter. */
async function testHoldStepPlusKnobLocks() {
    console.log('hold a step + turn a knob writes a parameter lock');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(stepDown(2));   /* hold step 3 */
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));         /* knob 1, +1  */

    const lockWrites = ctx.writes.filter((w) => /^lock\d+_\d+$/.test(w.key));
    check(lockWrites.length === 1,
          `expected one lock write, got ${JSON.stringify(ctx.writes)}`);
    if (lockWrites.length) {
        check(lockWrites[0].key === 'lock2_0',
              `expected lock2_0 (step 3, SRC knob A), got ${lockWrites[0].key}`);
    }
    const baseWrites = ctx.writes.filter((w) => /^(src|fx\d)_p\d$/.test(w.key));
    check(baseWrites.length === 0,
          `the base parameter must not move while locking, got ${JSON.stringify(baseWrites)}`);

    /* releasing after a lock must NOT also toggle the trig off */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(stepUp(2));
    const stepWrites = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(stepWrites.length === 0,
          `release after locking should not rewrite the step, got ${JSON.stringify(stepWrites)}`);
}

/* The v2 lock map is CONTIGUOUS across the stages: SRC at 0-7, FX 1 at 8-15,
 * FX 2 at 16-23, then the three machine selects. Get this wrong and holding a
 * step while turning a knob on FX 2 writes a lock onto a machine select — the
 * patch would change machine mid-pattern and nothing would say why. */
async function testLastStageLocksAppendRatherThanCollide() {
    console.log("FX 2's locks land at 16-23, below the machine selects");
    const ctx = await loadUI();
    ctx.host.init();

    /* focus FX 2: the stage pad cycles SRC -> FX 1 -> FX 2 */
    for (let i = 0; i < 2; i++) {
        ctx.host.onMidiMessageInternal(noteOn(70));
        ctx.host.onMidiMessageInternal(noteOff(70));
    }
    ctx.host.tick();

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(stepDown(2));          /* hold step 3 */
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));         /* knob 1, +1  */

    const locks = ctx.writes.filter((w) => /^lock\d+_\d+$/.test(w.key));
    check(locks.length === 1,
          `expected one lock write, got ${JSON.stringify(ctx.writes)}`);
    if (locks.length) {
        check(locks[0].key === 'lock2_16',
              `FX 2 knob A must lock index 16, got ${locks[0].key} — 24 is ` +
              `the SRC machine select, so an off-by-map here silently ` +
              `changes machine mid-pattern`);
    }
    ctx.host.onMidiMessageInternal(stepUp(2));

    /* and the knob edits FX 2's base parameter, not SRC's */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    const base = ctx.writes.filter((w) => /^(src|fx\d)_p\d$/.test(w.key));
    check(base.length === 1 && base[0].key === 'fx2_p1',
          `knob 1 with FX 2 focused wrote ${JSON.stringify(base)}, expected fx2_p1`);
}

/* Nudging an existing lock must start from the LOCK's value, not the base —
 * this is what the missing lock<N>_<P> getter used to break. */
async function testLockNudgeStartsFromLock() {
    console.log('nudging an existing lock continues from the locked value');
    const ctx = await loadUI();
    ctx.host.init();

    /* step 4 (index 3) has lock 0 = 100 in the fixture; base fx1_p1 is 76 */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(stepDown(3));
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));

    const w = ctx.writes.find((x) => x.key === 'lock3_0');
    check(!!w, 'no write to lock3_0');
    if (w) {
        check(`${w.val}` === '101',
              `expected 101 (locked 100 + 1), got ${w.val} — the UI fell back to the base value`);
    }
}

async function testPlainTapTogglesTrig() {
    console.log('tapping a step with no edit toggles its trig');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(stepDown(5));
    ctx.host.onMidiMessageInternal(stepUp(5));

    const stepWrites = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(stepWrites.length === 1, `expected one step write, got ${stepWrites.length}`);
    if (stepWrites.length) {
        check(stepWrites[0].key === 'step5', `expected step5, got ${stepWrites[0].key}`);
        check(/^1:/.test(stepWrites[0].val),
              `empty step should turn on, got ${stepWrites[0].val}`);
    }
}

async function testShiftEscapesTheLockGesture() {
    console.log('shift + knob edits the base value even while a step is held');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(stepDown(2));
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));

    const lockWrites = ctx.writes.filter((w) => /^lock\d+_\d+$/.test(w.key));
    const baseWrites = ctx.writes.filter((w) => /^(src|fx\d)_p\d$/.test(w.key));
    check(lockWrites.length === 0, 'shift + knob must not create a lock');
    check(baseWrites.length === 1,
          `shift + knob should edit the base, got ${JSON.stringify(ctx.writes)}`);
}

async function testMachinePaletteLoadsMachines() {
    console.log('palette pads load machines into the focused stage');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(noteOn(92));           /* palette index 0 */
    ctx.host.onMidiMessageInternal(noteOff(92));
    let w = ctx.writes.find((x) => x.key === 'src');
    check(!!w && `${w.val}` === `${SRC_FAMILY[0]}`,
          `pad 92 should load source ${SRC_FAMILY[0]} into SRC, got ${w && w.val}`);

    /* focus the next stage, then load again. The palette is a different FAMILY
     * now, so the same pad position means a different machine. */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(70));           /* PAD_STAGE */
    ctx.host.onMidiMessageInternal(noteOff(70));
    ctx.host.onMidiMessageInternal(noteOn(99));           /* palette index 7 */
    ctx.host.onMidiMessageInternal(noteOff(99));
    w = ctx.writes.find((x) => x.key === 'fx1');
    check(!!w && `${w.val}` === `${FX_FAMILY[7]}`,
          `pad 99 should load effect ${FX_FAMILY[7]} into FX 1, got ${w && w.val}`);
}

/* The SRC stage takes six machines and the pads offer twenty-one positions.
 * The fifteen spare pads must be DEAD, not wrap around or load an effect the
 * engine would refuse — a pad that silently does nothing is a small confusion,
 * a pad that loads a reverb into the source stage is a broken patch. */
async function testPaletteRefusesOutOfFamilyPads() {
    console.log('palette pads past the focused stage\'s family are dead');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    /* SRC is focused at init. Palette position 7 is past the six sources. */
    ctx.host.onMidiMessageInternal(noteOn(99));
    ctx.host.onMidiMessageInternal(noteOff(99));
    check(!ctx.writes.some((x) => x.key === 'src'),
          `a pad past the source family loaded something: ${JSON.stringify(ctx.writes)}`);

    /* And it is dark rather than left showing the previous stage's machine. */
    ctx.host.tick();
    check(ctx.leds.get(99) === 0,
          `pad 99 should be dark on the SRC stage, got ${ctx.leds.get(99)}`);
}

async function testTransportPads() {
    console.log('transport pads drive the sequencer');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(noteOn(68));           /* PLAY toggles */
    ctx.host.onMidiMessageInternal(noteOff(68));
    check(ctx.writes.some((w) => w.key === 'seq_on'), 'play pad did not write seq_on');

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(69));           /* FILL */
    ctx.host.onMidiMessageInternal(noteOff(69));
    check(ctx.writes.some((w) => w.key === 'fill'), 'fill pad did not write fill');
}

async function testJogSetsLengthAndStepAttrs() {
    console.log('jog sets pattern length, or the held step attribute in a mode');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(cc(JOG, 1));           /* free jog */
    check(ctx.writes.some((w) => w.key === 'seq_len'),
          `free jog should set length, got ${JSON.stringify(ctx.writes)}`);

    /* condition mode, then hold a step and jog */
    ctx.writes.length = 0;
    holdShift(ctx, true);      /* shift + pad 72 = COND */
    ctx.host.onMidiMessageInternal(noteOn(72));
    ctx.host.onMidiMessageInternal(noteOff(72));
    holdShift(ctx, false);
    ctx.host.onMidiMessageInternal(stepDown(1));
    ctx.host.onMidiMessageInternal(cc(JOG, 1));

    const stepWrite = ctx.writes.find((w) => w.key === 'step1');
    check(!!stepWrite, 'jog in condition mode did not write the step');
    if (stepWrite) {
        const cond = parseInt(`${stepWrite.val}`.split(':')[1], 10);
        check(cond === 1, `expected condition to advance to 1, got ${cond}`);
    }
}

async function testCopyPasteClear() {
    console.log('copy, paste and clear act on the visible page');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.host.onMidiMessageInternal(noteOn(73));           /* COPY  */
    ctx.host.onMidiMessageInternal(noteOff(73));
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(74));           /* PASTE */
    ctx.host.onMidiMessageInternal(noteOff(74));
    const pasted = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(pasted.length === 16, `paste should write 16 steps, wrote ${pasted.length}`);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(75));           /* CLEAR, short tap */
    ctx.host.onMidiMessageInternal(noteOff(75));
    const cleared = ctx.writes.filter((w) => /^step\d+$/.test(w.key) && `${w.val}` === '0:0:0:0');
    check(cleared.length === 16, `page clear should blank 16 steps, blanked ${cleared.length}`);
}

async function testNoUnknownWritesAnywhere() {
    console.log('every key the UI writes is one the engine accepts');
    const ctx = await loadUI();
    ctx.host.init();

    /* exercise a broad slice of the surface */
    for (const pad of [68, 69, 70, 71, 72, 73, 74, 80, 81, 82, 83, 92, 95, 99]) {
        ctx.host.onMidiMessageInternal(noteOn(pad));
        ctx.host.onMidiMessageInternal(noteOff(pad));
    }
    for (let s = 0; s < 16; s++) {
        ctx.host.onMidiMessageInternal(cc(STEP1 + s, 127));
        ctx.host.onMidiMessageInternal(cc(KNOB1 + (s % 8), 1));
        ctx.host.onMidiMessageInternal(cc(JOG, 1));
        ctx.host.onMidiMessageInternal(cc(STEP1 + s, 0));
    }
    for (let i = 0; i < 40; i++) ctx.host.tick();

    check(ctx.unknownWrites.size === 0,
          `UI wrote keys the engine does not accept: ${[...ctx.unknownWrites].join(', ')}`);
    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
}

/* A suspended overtake session resumes with its LEDs cleared; one paintAll is
 * ~60 writes in a tick and the shim's queue drops some. Overwork must force
 * several spaced repaints (the Smack v0.9.1 fix). */
async function testResumeForcesRepaints() {
    console.log('resume forces repeated full LED repaints');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.leds.clear();
    ctx.host.onResume();
    check(ctx.leds.size > 20, `onResume painted only ${ctx.leds.size} LEDs`);

    let repaints = 0;
    for (let i = 0; i < 40; i++) {
        ctx.leds.clear();
        ctx.host.tick();
        if (ctx.leds.size > 20) repaints++;
    }
    check(repaints >= 3, `expected at least 3 forced repaints after resume, saw ${repaints}`);
}

/* --------------------------------------------------------- v0.3.0 gestures */

async function testLiveRecordToggle() {
    console.log('shift + play arms live record');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(68));
    ctx.host.onMidiMessageInternal(noteOff(68));
    holdShift(ctx, false);
    const w = ctx.writes.find((x) => x.key === 'live_rec');
    check(!!w && `${w.val}` === '1', `shift+play did not arm live_rec (${w && w.val})`);
    /* unshifted play must still be play, not record */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(68));
    ctx.host.onMidiMessageInternal(noteOff(68));
    check(ctx.writes.some((x) => x.key === 'seq_on'), 'plain play stopped writing seq_on');
}

async function testProbabilityMode() {
    console.log('shift + pattern-page selects probability mode, jog sets it');
    const ctx = await loadUI();
    ctx.host.init();
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(71));
    ctx.host.onMidiMessageInternal(noteOff(71));
    holdShift(ctx, false);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(stepDown(4));   /* hold step 5 */
    ctx.host.onMidiMessageInternal(cc(JOG, 127));          /* jog down    */
    const w = ctx.writes.find((x) => x.key === 'prob4');
    check(!!w, `jog in probability mode did not write prob4; got ${JSON.stringify(ctx.writes)}`);
    if (w) check(parseInt(`${w.val}`, 10) < 100,
                 `probability should have come down from 100, got ${w.val}`);
}

/* The five source machines already spend all eight knobs, so the filter lives
 * on its own page. A page nothing can reach is the failure this repo keeps
 * hitting — correct code, no gesture. */
async function testVoiceFilterPageIsReachable() {
    console.log('the voice filter has its own reachable edit page');
    const ctx = await loadUI();
    ctx.host.init();

    let seen = null;
    for (let i = 0; i < 12 && !seen; i++) {
        ctx.host.tick();
        const shown = ctx.screen.map((x) => x.text).join(' ');
        if (/VOICE/.test(shown)) seen = shown;
        else {
            ctx.host.onMidiMessageInternal(noteOn(72));
            ctx.host.onMidiMessageInternal(noteOff(72));
        }
    }
    check(!!seen, 'no edit page shows the voice filter');
    if (seen) {
        for (const lab of ['BASE', 'WDTH', 'RESO', 'ENV', 'ATK', 'DEC', 'KEY']) {
            check(seen.indexOf(lab) >= 0, `the filter page is missing ${lab}: "${seen}"`);
        }
    }

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    const w = ctx.writes.find((x) => x.key === 'vf_base');
    check(!!w, `knob 1 on the filter page wrote ${JSON.stringify(ctx.writes)}, ` +
               `expected vf_base`);
}

async function testLfo3AndEnvelopePages() {
    console.log('the edit pages reach LFO 3 and the modulation envelope');
    const ctx = await loadUI();
    ctx.host.init();
    const seen = new Set();
    for (let i = 0; i < 8; i++) {                 /* cycle every edit page */
        ctx.writes.length = 0;
        for (let k = 0; k < 8; k++) ctx.host.onMidiMessageInternal(cc(KNOB1 + k, 1));
        ctx.writes.forEach((x) => seen.add(x.key.replace(/\d+$/, '')));
        ctx.host.onMidiMessageInternal(noteOn(72));
        ctx.host.onMidiMessageInternal(noteOff(72));
    }
    check([...seen].some((k) => k.startsWith('lfo3_')),
          `no LFO 3 parameter was reachable; saw ${[...seen].join(', ')}`);
    check([...seen].some((k) => k.startsWith('menv_')),
          `no envelope parameter was reachable; saw ${[...seen].join(', ')}`);
}

/* Knob response has now been wrong in BOTH directions on hardware, so this
 * pins the exact numbers rather than a range.
 *
 * decodeDelta returns ACCUMULATED movement — up to 63 from one event. Applied
 * raw to the 21-entry machine select it hit an end stop every time ("fx 2 only
 * does warble or bypass"); clamped to one step per event, crossing the list
 * took twenty separate clicks ("super slow"). The rule is a cap of a quarter
 * of the range: one detent moves one, a full-speed spin moves ceil(span/4). */
/* Walk the edit pages until the machine selects are on screen, rather than
 * pressing a fixed number of times. A count here breaks whenever a page is
 * added between FX and GLOBAL — which is what adding the voice-filter page
 * did to six tests at once. */
async function gotoGlobalPage(ctx) {
    for (let i = 0; i < 12; i++) {
        ctx.host.tick();
        if (ctx.screen.some((x) => /GLOBAL/.test(x.text))) return;
        ctx.host.onMidiMessageInternal(noteOn(72));
        ctx.host.onMidiMessageInternal(noteOff(72));
    }
    ctx.host.tick();
    throw new Error('never reached the GLOBAL edit page: ' +
                    JSON.stringify(ctx.screen.map((x) => x.text)));
}

/* Start the UI with a chosen value already in the DSP, on the GLOBAL page.
 * The value has to be in the store BEFORE init — the UI mirrors the DSP at
 * load, and deliberately does not re-read on every knob event. */
async function atGlobalWith(seed) {
    const ctx = await loadUI();
    Object.assign(ctx.store, seed);
    ctx.host.init();
    await gotoGlobalPage(ctx);
    ctx.writes.length = 0;
    return ctx;
}

/* A machine knob steps through its stage's FAMILY, so both the acceleration
 * cap and the end stops come from that family's length — not from the length of
 * the whole machine list. Both families are checked because they are very
 * different sizes (six sources, twenty-one effects) and the cap arithmetic is
 * where an off-by-one would hide. */
async function stepMachineKnob(stage, fam, fromPos, delta) {
    const seed = {};
    seed[STAGE_KEY[stage]] = `${fam[fromPos]}`;
    const ctx = await atGlobalWith(seed);
    ctx.host.onMidiMessageInternal(cc(KNOB1 + stage, delta));
    const w = ctx.writes.find((x) => x.key === STAGE_KEY[stage]);
    return w ? parseInt(`${w.val}`, 10) : null;
}

async function testKnobResponseCurve() {
    console.log('knob response: one detent moves one, a fast spin moves a quarter of the range');

    for (const [stage, fam, name] of [[0, SRC_FAMILY, 'SRC'], [1, FX_FAMILY, 'FX 1']]) {
        const cap = Math.ceil((fam.length - 1) / 4);

        let got = await stepMachineKnob(stage, fam, 1, 1);        /* one detent */
        check(got === fam[2],
              `${name}: one detent moved to ${got} — expected ${fam[2]}, the next ` +
              `machine in the family rather than the next machine CODE`);

        got = await stepMachineKnob(stage, fam, 1, 25);           /* full-speed spin */
        check(got === fam[1 + cap],
              `${name}: a 25-detent event moved to ${got} — expected ${fam[1 + cap]}: ` +
              `neither an end stop nor a single step`);

        /* the end of each family must be REACHABLE — Granulator was excluded
         * when this range was a hardcoded constant */
        got = await stepMachineKnob(stage, fam, fam.length - 2, 40);
        check(got === fam[fam.length - 1],
              `${name}: could not reach the last machine in the family ` +
              `(${fam[fam.length - 1]}); got ${got}`);
    }

    /* wide ranges keep the acceleration, or 0-127 becomes unusable */
    const ctx = await atGlobalWith({ mix: '40' });
    ctx.host.onMidiMessageInternal(cc(KNOB1 + MIX_KNOB, 20));   /* MIX, 0-127 */
    const m = ctx.writes.find((x) => x.key === 'mix');
    check(m && parseInt(`${m.val}`, 10) === 60,
          `wide-range acceleration was lost: mix went to ${m && m.val}, expected 60`);
}

/* Every read is a blocking round-trip to the shim serviced once per SPI frame.
 * fetchAll wants ~58 keys; one at a time that is over a second of stall, and it
 * runs from the machine-select handler. It must use the bulk path. */
async function testFetchAllUsesBulkReads() {
    console.log('a full refresh costs a couple of round-trips, not sixty');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.roundTrips.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(PALETTE_ORDER[1]));   /* load a machine */
    ctx.host.onMidiMessageInternal(noteOff(PALETTE_ORDER[1]));

    check(ctx.roundTrips.length > 0, 'loading a machine refreshed nothing');
    check(ctx.roundTrips.length <= 4,
          `a machine change cost ${ctx.roundTrips.length} round-trips — at ~23 ms ` +
          `each that is the "super slow" stall; batch them with get_params`);
    const bulk = ctx.roundTrips.filter((r) => r.bulk).length;
    check(bulk > 0, 'the bulk get_params path was never used');
}

/* The bulk wire format is schwung's, not ours: "<count>\n" then count records
 * of "<len>\n<bytes>". Decode it wrong and every value shifts by one key —
 * which would look like working software right up until a knob edits the wrong
 * parameter. The mock implements the format from the shim's own parser; this
 * proves the UI reads real values back out of it, by nudging a value it could
 * only have got from a bulk response.
 *
 * `machines` is variable-length and sits in the same batch, so a naive decoder
 * that assumed fixed records would land somewhere else entirely. */
async function testBulkDecodeIsPositionallyCorrect() {
    console.log('bulk-read values land on the right keys');
    const seed = { mix: '99' };
    seed[STAGE_KEY[1]] = `${FX_FAMILY[13]}`;
    const ctx = await atGlobalWith(seed);

    ctx.host.onMidiMessageInternal(cc(KNOB1 + 1, 1));       /* FX 1 machine +1 */
    const w = ctx.writes.find((x) => x.key === STAGE_KEY[1]);
    check(w && parseInt(`${w.val}`, 10) === FX_FAMILY[14],
          `the FX 1 machine continued from the wrong base: wrote ${w && w.val}, ` +
          `expected ${FX_FAMILY[14]}`);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1 + MIX_KNOB, 1));   /* mix +1 */
    const m = ctx.writes.find((x) => x.key === 'mix');
    check(m && parseInt(`${m.val}`, 10) === 100,
          `mix continued from the wrong base: wrote ${m && m.val}, expected 100`);
}

/* -------------------------------------------------------- feedback guard */

function withJack(ctx, speakers, lineIn) {
    ctx.host.host_speaker_active = () => speakers;
    ctx.host.host_line_in_connected = () => lineIn;
}

async function testFeedbackGuardArmsOnRisk() {
    console.log('the feedback guard mutes the input when the mic can hear the speakers');
    const ctx = await loadUI();
    ctx.store.hw_input = '1';
    withJack(ctx, true, true);            /* speakers on, but a cable is in */
    ctx.host.init();
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor' && `${w.val}` === '0'),
          'guard muted with a cable plugged in — that is not a feedback path');

    /* pull the cable: speakers live, mic open */
    withJack(ctx, true, false);
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    const muted = ctx.writes.find((w) => w.key === 'monitor');
    check(!!muted && `${muted.val}` === '0',
          `guard did not mute on risk; writes were ${JSON.stringify(ctx.writes)}`);

    /* plug back in: it must restore, not stay muted forever */
    withJack(ctx, true, true);
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    const restored = ctx.writes.find((w) => w.key === 'monitor');
    check(!!restored && `${restored.val}` === '1',
          `guard did not restore the input when the risk cleared (${restored && restored.val})`);
}

async function testGuardSilentForChainBuild() {
    console.log('the guard stays out of the way when the build does not read the mic');
    const ctx = await loadUI();
    ctx.store.hw_input = '0';             /* the audio_fx build */
    withJack(ctx, true, false);           /* would be risky IF it read the mic */
    ctx.host.init();
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor'),
          'the guard armed for a build that processes upstream chain audio');
}

async function testMonitorManualOverride() {
    console.log('shift + fill overrides the guard');
    const ctx = await loadUI();
    ctx.store.hw_input = '1';
    withJack(ctx, true, false);
    ctx.host.init();
    for (let i = 0; i < 30; i++) ctx.host.tick();

    ctx.writes.length = 0;
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(69));
    ctx.host.onMidiMessageInternal(noteOff(69));
    holdShift(ctx, false);
    const on = ctx.writes.find((w) => w.key === 'monitor');
    check(!!on && `${on.val}` === '1', `override did not unmute (${on && on.val})`);

    /* and the guard must not immediately stamp on the override */
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor' && `${w.val}` === '0'),
          'the guard overrode the user while the risk state was unchanged');
}

/* ---------------------------------------------------------------- presets */

const PDIR = '/data/UserData/schwung/presets/overwork';

/* Open the preset browser: Shift + jog click. */
function openPresets(ctx) {
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(cc(3, 127));      /* MoveMainButton */
    holdShift(ctx, false);
    ctx.host.tick();                                 /* the device redraws on tick */
}

/* THE guard on the whole approach. If the mock's os.readdir were written from
 * the UI's assumptions — a flat array of filenames — this test would pass
 * against a broken implementation. So assert the mock reproduces the REAL
 * contract, and that the naive reading of it fails the way Mono did. */
async function testReaddirContractIsFaithful() {
    console.log('the os.readdir mock reproduces the real tuple contract');
    const ctx = await loadUI();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/one.json`, '{"name":"One","state":"{}"}');

    const raw = ctx.vfs.readdir(PDIR);
    check(Array.isArray(raw) && Array.isArray(raw[0]),
          'readdir must answer a [names, errno] tuple, got ' + JSON.stringify(raw));
    check(raw[0].includes('.') && raw[0].includes('..'),
          'a real listing includes "." and ".."; mock gave ' + JSON.stringify(raw[0]));
    check(raw[1] === 0, 'errno slot should be 0 on success, got ' + raw[1]);

    /* the naive implementation Mono shipped, run against this same mock */
    const naive = (() => {
        const names = ctx.vfs.readdir(PDIR);      /* treated as a flat array */
        try { return /\.json$/i.test(names) ? [String(names).replace(/\.json$/i, '')] : []; }
        catch (e) { return ['THREW']; }
    })();
    check(naive.length === 0 || naive[0] === 'THREW',
          'the naive flat-array reading should find nothing (or throw) against the ' +
          'real contract — it "found" ' + JSON.stringify(naive) +
          ', so the mock is too forgiving to catch the Mono bug');

    /* os.rename and os.remove must report failure by return code, not throw */
    ctx.vfs.failRenames(true);
    let threw = false;
    let rc = 0;
    try { rc = ctx.vfs.rename(`${PDIR}/one.json`, `${PDIR}/two.json`); }
    catch (e) { threw = true; }
    check(!threw && rc < 0, 'a failing rename must return -errno, not throw');
    ctx.vfs.failRenames(false);
    check(ctx.vfs.remove(`${PDIR}/nope.json`) < 0, 'removing a missing file must return -errno');
}

/* THE bug this feature exists to close: a source-machine preset restored every
 * parameter, LFO, pattern and lock, and then played silence. The audio is not
 * in the patch file — a few seconds of stereo does not fit a 64 KiB blob — so
 * the patch records the PATH and the UI fetches the audio back. */
async function testPresetRestoresItsSample() {
    console.log('loading a preset fetches back the sample it was saved with');
    const dir = '/data/UserData/UserLibrary/Samples';

    /* --- save half: a patch with a sample must record where it came from --- */
    const a = await loadUI();
    a.host.init();
    a.vfs.dirs.add(dir);
    a.vfs.binaries.set(`${dir}/kit.wav`, makeWav({ frames: 600 }));
    check(a.host.loadSampleFile(`${dir}/kit.wav`), 'the fixture sample did not load');
    check(a.store.sample_path === `${dir}/kit.wav`,
          `the engine was told the path was "${a.store.sample_path}"`);

    openPresets(a);
    a.host.onMidiMessageInternal(cc(3, 127));            /* "Save new" */
    const file = [...a.vfs.files.keys()].find((f) => f.endsWith('.json'));
    check(!!file, 'nothing was saved');
    const saved = JSON.parse(a.vfs.files.get(file));
    check(/"smp":"/.test(saved.state),
          `the saved patch does not record its sample: ${saved.state.slice(0, 120)}`);

    /* --- load half: a FRESH session holding nothing, which is what a reboot
     * or someone else's preset actually looks like --- */
    const b = await loadUI();
    b.host.init();
    b.vfs.dirs.add(dir);
    b.vfs.binaries.set(`${dir}/kit.wav`, makeWav({ frames: 600 }));
    b.host.host_module_set_param('sample_clear', '1');
    b.host.host_ensure_dir(PDIR);
    b.host.host_write_file(`${PDIR}/kitpatch.json`, JSON.stringify(saved));

    openPresets(b);
    b.writes.length = 0;
    b.host.onMidiMessageInternal(cc(3, 127));            /* click loads index 1 */

    check(b.writes.some((w) => w.key === 'state'),
          `the click did not load a preset; writes were ${JSON.stringify(b.writes.map((w) => w.key))}`);
    check(b.writes.some((w) => w.key === 'sample_begin'),
          'the preset loaded but never fetched its audio back');
    check(parseInt(b.store.sample_frames, 10) === 600,
          `engine holds ${b.store.sample_frames} frames after the preset load`);
}

/* A preset whose file has moved must say so and leave what is loaded alone.
 * Dropping the current sample would turn "this patch's file moved" into
 * "everything is silent now", which is the worse of the two failures. */
async function testPresetWithAMissingSampleIsSurvivable() {
    console.log('a preset naming a sample that is gone reports it and keeps the old one');
    const ctx = await loadUI();
    ctx.host.init();
    const dir = '/data/UserData/UserLibrary/Samples';
    ctx.vfs.dirs.add(dir);
    ctx.vfs.binaries.set(`${dir}/here.wav`, makeWav({ frames: 500 }));
    check(ctx.host.loadSampleFile(`${dir}/here.wav`), 'the fixture sample did not load');

    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/gone.json`, JSON.stringify({
        name: 'Gone',
        state: `{"v":1,"mix":64,"smp":"${dir}/vanished.wav"}`
    }));
    openPresets(ctx);
    ctx.host.onMidiMessageInternal(cc(3, 127));          /* click loads index 1 */
    ctx.host.tick();

    check(parseInt(ctx.store.sample_frames, 10) === 500,
          'the missing file wiped the sample that was already loaded');
    const said = ctx.spoken.join(' | ');
    check(/Missing/i.test(said),
          `nothing reported the missing file; it said "${said}"`);
}

async function testPresetSaveThenList() {
    console.log('saving a preset writes a file the browser can then list');
    const ctx = await loadUI();
    ctx.host.init();

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* click on "Save new" */

    const written = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.json'));
    check(written.length === 1, `expected one preset file, got ${JSON.stringify(written)}`);
    check(!written.some((f) => f.endsWith('.tmp')), 'a .tmp file was left behind');

    const payload = JSON.parse(ctx.vfs.files.get(written[0]));
    check(!!payload.state, 'preset carries no state blob');
    check(payload.module === 'overwork', `preset module tag is ${payload.module}`);

    /* the saved preset must now appear in the list — the exact step that
     * silently did nothing in Mono */
    ctx.host.tick();
    const shown = ctx.screen.map((l) => l.text).join(' ');
    check(/Pattern 1/.test(shown),
          `saved preset does not appear in the browser; screen shows: ${shown}`);
}

async function testPresetLoadRestoresState() {
    console.log('loading a preset pushes its state back to the engine');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/saved.json`,
        JSON.stringify({ v: 1, name: 'Saved', module: 'overwork',
                         state: '{"v":1,"mix":42,"m1":5,"p1":[1,2,3,4,5,6,7,8]}' }));

    openPresets(ctx);
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* click loads index 1 */

    const w = ctx.writes.find((x) => x.key === 'state');
    check(!!w, `no state write on load; writes were ${JSON.stringify(ctx.writes.slice(0,4))}`);
    if (w) check(/"mix":42/.test(`${w.val}`), `state pushed was ${w.val}`);
}

async function testPresetDelete() {
    console.log('the clear pad deletes the selected preset');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/gone.json`, '{"name":"Gone","state":"{}"}');

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(noteOn(75));       /* PAD_CLEAR */
    ctx.host.onMidiMessageInternal(noteOff(75));
    check(!ctx.vfs.files.has(`${PDIR}/gone.json`), 'preset file survived delete');
}

/* If the rename step fails, the payload must still reach its destination
 * rather than being stranded in the .tmp file. */
async function testPresetSurvivesRenameFailure() {
    console.log('a refused rename still saves the preset');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.failRenames(true);

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* Save new */

    const finals = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.json'));
    const temps = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.tmp'));
    check(finals.length === 1, `preset not saved when rename failed: ${JSON.stringify([...ctx.vfs.files.keys()])}`);
    check(temps.length === 0, 'a .tmp file was stranded after the rename failure');
}

/* An empty or missing directory must give an empty list, never an exception —
 * a throw here is fatal to the whole overtake session. */
async function testPresetEmptyDirIsSafe() {
    console.log('an empty or missing preset directory does not throw');
    const ctx = await loadUI();
    ctx.host.init();
    let threw = false;
    try {
        openPresets(ctx);                             /* dir does not exist yet */
        for (let i = 0; i < 5; i++) ctx.host.tick();
        ctx.host.host_ensure_dir(PDIR);               /* now exists but is empty */
        openPresets(ctx);
        for (let i = 0; i < 5; i++) ctx.host.tick();
    } catch (e) { threw = true; }
    check(!threw, 'the preset browser threw on an empty directory');

    /* a corrupt preset must not take the browser down either */
    ctx.host.host_write_file(`${PDIR}/bad.json`, 'not json at all');
    threw = false;
    try { openPresets(ctx); for (let i = 0; i < 5; i++) ctx.host.tick(); }
    catch (e) { threw = true; }
    check(!threw, 'a corrupt preset file threw');
}


/* ------------------------------------------------------------ Tier B: SRC */

/* A real RIFF/WAVE file, built here rather than checked in, so the parser is
 * tested against the format and not against a fixture that might itself be
 * wrong. `extra` inserts a LIST chunk BEFORE fmt — plenty of real WAVs carry
 * one, and a parser that assumes fmt sits at offset 12 reads metadata as
 * audio. */
function makeWav({ frames, channels = 2, bits = 16, rate = 44100, extra = false }) {
    const bytesPerSample = bits >> 3;
    const dataLen = frames * channels * bytesPerSample;
    const listLen = extra ? 12 : 0;
    const total = 12 + listLen + 24 + 8 + dataLen;
    const b = Buffer.alloc(total);
    let at = 0;
    b.write('RIFF', at); at += 4;
    b.writeUInt32LE(total - 8, at); at += 4;
    b.write('WAVE', at); at += 4;
    if (extra) {
        b.write('LIST', at); at += 4;
        b.writeUInt32LE(4, at); at += 4;
        b.write('INFO', at); at += 4;
    }
    b.write('fmt ', at); at += 4;
    b.writeUInt32LE(16, at); at += 4;
    b.writeUInt16LE(bits === 32 ? 3 : 1, at); at += 2;    /* 3 = IEEE float */
    b.writeUInt16LE(channels, at); at += 2;
    b.writeUInt32LE(rate, at); at += 4;
    b.writeUInt32LE(rate * channels * bytesPerSample, at); at += 4;
    b.writeUInt16LE(channels * bytesPerSample, at); at += 2;
    b.writeUInt16LE(bits, at); at += 2;
    b.write('data', at); at += 4;
    b.writeUInt32LE(dataLen, at); at += 4;
    for (let f = 0; f < frames; f++) {
        for (let c = 0; c < channels; c++) {
            const v = ((f * (c + 1) * 13) % 20000) - 10000;
            if (bits === 16) b.writeInt16LE(v, at);
            else if (bits === 8) b.writeUInt8(((v >> 8) + 128) & 0xFF, at);
            else if (bits === 24) { b.writeUInt8(0, at); b.writeInt16LE(v, at + 1); }
            else if (bits === 32) b.writeFloatLE(v / 32768, at);
            at += bytesPerSample;
        }
    }
    return b;
}

/* Decode what the UI actually sent, using the engine's own wire format. */
function decodeSent(writes) {
    const begin = writes.find((w) => w.key === 'sample_begin');
    const chunks = writes.filter((w) => w.key === 'sample_chunk');
    const ended = writes.some((w) => w.key === 'sample_end');
    if (!begin) return null;
    const bytes = Buffer.concat(chunks.map((c) => Buffer.from(`${c.val}`, 'base64')));
    return {
        frames: parseInt(`${begin.val}`, 10),
        name: `${begin.val}`.split(':')[1] || '',
        bytes, ended, chunkCount: chunks.length
    };
}

async function testWavLoadRoundTrip() {
    console.log('a 16-bit stereo WAV loads and transfers byte-exact');
    const ctx = await loadUI();
    ctx.host.init();

    const wav = makeWav({ frames: 1000 });
    ctx.vfs.dirs.add('/data/UserData/Samples');
    ctx.vfs.binaries.set('/data/UserData/Samples/kick.wav', wav);

    ctx.writes.length = 0;
    const ok = ctx.host.loadSampleFile('/data/UserData/Samples/kick.wav');
    check(ok === true, 'loadSampleFile reported failure on a valid WAV');

    const sent = decodeSent(ctx.writes);
    check(!!sent, 'nothing was sent to the engine');
    if (sent) {
        check(sent.ended, 'the transfer never committed with sample_end');
        check(sent.frames === 1000, `declared ${sent.frames} frames, expected 1000`);
        check(sent.name === 'kick', `sample name was "${sent.name}", expected kick`);
        check(sent.bytes.length === 1000 * 4,
              `sent ${sent.bytes.length} bytes, expected ${1000 * 4}`);
        const src = wav.subarray(wav.length - 1000 * 4);
        check(Buffer.compare(sent.bytes, src) === 0,
              'transferred audio does not match the file');
    }
}

async function testWavVariantsAndChunkParsing() {
    console.log('mono, 8/24/32-bit and chunk-padded WAVs all convert to stereo 16-bit');
    for (const spec of [
        { frames: 300, channels: 1, bits: 16, label: 'mono 16-bit' },
        { frames: 300, channels: 2, bits: 8,  label: 'stereo 8-bit' },
        { frames: 300, channels: 2, bits: 24, label: 'stereo 24-bit' },
        { frames: 300, channels: 2, bits: 32, label: 'stereo float' },
        { frames: 300, channels: 2, bits: 16, extra: true, label: 'LIST chunk before fmt' }
    ]) {
        const ctx = await loadUI();
        ctx.host.init();
        ctx.vfs.dirs.add('/data/UserData/Samples');
        ctx.vfs.binaries.set('/data/UserData/Samples/x.wav', makeWav(spec));
        ctx.writes.length = 0;
        ctx.host.loadSampleFile('/data/UserData/Samples/x.wav');
        const sent = decodeSent(ctx.writes);
        check(sent && sent.frames === 300 && sent.bytes.length === 300 * 4,
              `${spec.label}: sent ${sent && sent.frames} frames / ` +
              `${sent && sent.bytes.length} bytes, expected 300 / 1200`);
        if (spec.channels === 1 && sent) {
            check(sent.bytes.readInt16LE(0) === sent.bytes.readInt16LE(2),
                  'mono was not duplicated across both channels');
        }
    }
}

/* The engine's buffer is finite. The UI must clamp to what sample_max reports
 * rather than sending frames the engine will drop — a mismatch between the
 * declared length and the audio is how a transfer goes silently out of sync. */
async function testOversizedSampleIsTruncated() {
    console.log('a sample longer than the engine buffer is truncated before sending');
    const ctx = await loadUI();
    ctx.store.sample_max = '500';
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/Samples');
    ctx.vfs.binaries.set('/data/UserData/Samples/long.wav', makeWav({ frames: 4000 }));
    ctx.writes.length = 0;
    ctx.host.loadSampleFile('/data/UserData/Samples/long.wav');
    const sent = decodeSent(ctx.writes);
    check(sent && sent.frames === 500, `declared ${sent && sent.frames}, expected 500`);
    check(sent && sent.bytes.length === 500 * 4,
          `sent ${sent && sent.bytes.length} bytes for a 500-frame declaration`);
}

async function testSampleTransferIsChunked() {
    console.log('a large transfer is split into chunks the param channel can carry');
    const ctx = await loadUI();
    ctx.store.sample_max = '200000';
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/Samples');
    ctx.vfs.binaries.set('/data/UserData/Samples/big.wav', makeWav({ frames: 60000 }));
    ctx.writes.length = 0;
    ctx.host.loadSampleFile('/data/UserData/Samples/big.wav');
    const sent = decodeSent(ctx.writes);
    check(sent && sent.chunkCount > 1,
          `60000 frames went in ${sent && sent.chunkCount} chunk(s)`);
    /* SHADOW_PARAM_VALUE_LEN is 65536; anything bigger is truncated in transit. */
    const biggest = Math.max(...ctx.writes
        .filter((w) => w.key === 'sample_chunk')
        .map((w) => `${w.val}`.length));
    check(biggest < 65536,
          `largest chunk was ${biggest} chars — over the 64 KB param buffer, so ` +
          'it would be truncated in transit');
}

async function testGarbageFileIsRejected() {
    console.log('a non-WAV file is refused rather than loaded as noise');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/Samples');
    ctx.vfs.binaries.set('/data/UserData/Samples/notes.txt', Buffer.from('hello there'));
    ctx.writes.length = 0;
    const ok = ctx.host.loadSampleFile('/data/UserData/Samples/notes.txt');
    check(ok === false, 'a text file was accepted as a sample');
    check(!ctx.writes.some((w) => w.key === 'sample_begin'),
          'a rejected file still started a transfer');
}


/* MACHINE_COLOR is indexed by machine but hand-maintained in JS while the
 * machine list lives in C — the same shape as the N_MACHINES constant that
 * made Granulator and then One Shot unreachable. A colour cannot be derived
 * from the engine, so the drift is caught here instead of on hardware. */
async function testMachineColorTableCoversEveryMachine() {
    console.log('every machine the engine lists has a palette colour');
    const ctx = await loadUI();
    ctx.host.init();
    const engine = ctx.store.machines.split(',').length;
    const colors = ctx.host.__machineColorCount();
    check(colors === engine,
          `MACHINE_COLOR has ${colors} entries, the engine lists ${engine} machines — ` +
          `machine ${Math.min(colors, engine)} would light with no colour of its own`);

    /* and the lookup must not hand undefined to setLED even if it does drift */
    const lit = [...ctx.leds.values()].filter((v) => v === undefined);
    check(lit.length === 0, `${lit.length} pads were lit with an undefined colour`);
}


/* The palette occupies pad rows 1-3, but three of those pads are undo, memo
 * and song. Mapping pad index straight to machine index was safe only while
 * the machine count stayed below the first function pad's index — at 21
 * machines nothing reached pad 81. Phase 3 pushed the count past it, and
 * pressing Undo would have loaded a machine instead of undoing. */
async function testPaletteNeverShadowsTheFunctionPads() {
    console.log('undo, memo and song are not swallowed by the machine palette');
    const ctx = await loadUI();
    ctx.host.init();

    for (const [pad, key] of [[81, 'undo'], [82, 'memo'], [83, 'song']]) {
        ctx.writes.length = 0;
        ctx.host.onMidiMessageInternal(noteOn(pad));
        ctx.host.onMidiMessageInternal(noteOff(pad));
        const loaded = ctx.writes.find((w) => STAGE_KEY.indexOf(w.key) >= 0);
        check(!loaded,
              `pad ${pad} (${key}) loaded machine ${loaded && loaded.val} instead ` +
              `of doing its own job`);
    }
}

/* Every machine the engine has must be reachable from the pads, not just from
 * the GLOBAL page knob — that is what the palette is for.
 *
 * The sweep walks the STAGES rather than a Shift bank: each stage shows its own
 * family, and between them the families have to cover the whole machine list.
 * This is also the check that the effect family still FITS — twenty-one effects
 * against twenty-one free pads is exact, so a twenty-second effect would fall
 * off the end of the palette and be reachable from nothing. */
async function testEveryMachineIsReachableFromThePalette() {
    console.log('every machine the engine lists can be loaded from a pad');
    const ctx = await loadUI();
    ctx.host.init();
    const total = ctx.store.machines.split(',').length;

    const reached = new Set();
    for (let stage = 0; stage < N_STAGES; stage++) {
        for (const pad of PALETTE_ORDER) {
            ctx.writes.length = 0;
            ctx.host.onMidiMessageInternal(noteOn(pad));
            ctx.host.onMidiMessageInternal(noteOff(pad));
            const w = ctx.writes.find((x) => STAGE_KEY.indexOf(x.key) >= 0);
            if (w) reached.add(parseInt(`${w.val}`, 10));
        }
        ctx.host.onMidiMessageInternal(noteOn(70));      /* next stage */
        ctx.host.onMidiMessageInternal(noteOff(70));
    }

    const missing = [];
    for (let i = 0; i < total; i++) if (!reached.has(i)) missing.push(i);
    check(missing.length === 0,
          `machines ${missing.join(', ')} of ${total} cannot be loaded from any ` +
          `pad on any stage — a family is bigger than the palette`);
}


/* Everything below the surface can be right while the feature is unreachable.
 * loadSampleFile existed, was tested, and had NO gesture wiring it to the pads
 * — so on hardware the whole SRC machine set was silent and there was no way
 * to fix that from the Move. These drive the GESTURE, not the function. */
async function testSampleBrowserIsReachableAndLoads() {
    console.log('the sample browser opens from the surface and loads a file');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/a.wav', makeWav({ frames: 400 }));
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/b.wav', makeWav({ frames: 800 }));

    /* SHIFT + slot pad opens it */
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    ctx.host.tick();

    const shown = ctx.screen.map((x) => x.text).join(' ');
    check(/SAMPLES/.test(shown), `browser did not draw; screen was "${shown}"`);
    check(/a\.wav|b\.wav/.test(shown), `browser listed no files; screen was "${shown}"`);

    /* jog click loads the highlighted one */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    const begin = ctx.writes.find((w) => w.key === 'sample_begin');
    const ended = ctx.writes.some((w) => w.key === 'sample_end');
    check(!!begin, 'jog click in the browser transferred nothing');
    check(ended, 'the transfer never committed');

    /* A successful load closes the browser, so reopen it to pick another —
     * that is the intended flow, not a workaround. */
    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);

    /* jog scrolls to the other file and loads that one instead */
    ctx.host.onMidiMessageInternal(cc(JOG, 1));
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    const second = ctx.writes.find((w) => w.key === 'sample_begin');
    check(second && `${second.val}` !== `${begin.val}`,
          `scrolling did not change which file loads (both declared ${begin && begin.val})`);
}

async function testSampleBrowserClosesTheWayItOpened() {
    console.log('the browser closes with the gesture that opened it');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/a.wav', makeWav({ frames: 400 }));

    const openClose = () => {
        holdShift(ctx, true);
        ctx.host.onMidiMessageInternal(noteOn(70));
        ctx.host.onMidiMessageInternal(noteOff(70));
        holdShift(ctx, false);
        ctx.host.tick();
    };
    openClose();
    openClose();
    const shown = ctx.screen.map((x) => x.text).join(' ');
    check(!/SAMPLES/.test(shown),
          `the browser would not close — a user could get stuck in it`);
}


/* The Move keeps its library under UserLibrary, and Schwung's own resampler
 * and skipback write into DATED SUBDIRECTORIES. A flat scan of the base
 * directory finds nothing at all — verified against the device, where 96 WAVs
 * live at Samples/Schwung/Skipback/<date>/. */
async function testSampleScanFindsNestedFiles() {
    console.log('samples in dated subdirectories are found');
    const ctx = await loadUI();
    ctx.host.init();

    const deep = '/data/UserData/UserLibrary/Samples/Schwung/Skipback/2026-07-28';
    for (const d of ['/data/UserData/UserLibrary/Samples',
                     '/data/UserData/UserLibrary/Samples/Schwung',
                     '/data/UserData/UserLibrary/Samples/Schwung/Skipback',
                     deep,
                     '/data/UserData/UserLibrary/Recordings']) ctx.vfs.dirs.add(d);
    ctx.vfs.binaries.set(`${deep}/skip.wav`, makeWav({ frames: 200 }));
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Recordings/rec.wav',
                         makeWav({ frames: 200 }));

    const found = ctx.host.listSamples();
    check(found.includes(`${deep}/skip.wav`),
          `the nested sample was not found; got ${JSON.stringify(found)}`);
    check(found.includes('/data/UserData/UserLibrary/Recordings/rec.wav'),
          `the recordings sample was not found; got ${JSON.stringify(found)}`);
}

/* A directory tree cannot be allowed to spin the walk forever, and the browser
 * is a browser rather than an archive. */
async function testSampleScanIsBounded() {
    console.log('the sample scan is depth- and count-bounded');
    const ctx = await loadUI();
    ctx.host.init();
    let dir = '/data/UserData/UserLibrary/Samples';
    ctx.vfs.dirs.add(dir);
    for (let i = 0; i < 12; i++) {
        dir = `${dir}/level${i}`;
        ctx.vfs.dirs.add(dir);
        ctx.vfs.binaries.set(`${dir}/s.wav`, makeWav({ frames: 100 }));
    }
    const found = ctx.host.listSamples();
    check(found.length > 0, 'the bounded scan found nothing at all');
    check(found.length < 12,
          `the scan descended all 12 levels (${found.length} files) — it must stop`);
}


/* A load that failed and a load that worked looked IDENTICAL on screen: the
 * only feedback was announce(), which reaches the screen reader and nothing
 * else. With it off there was no way to tell whether the feature worked —
 * reported from hardware as "the list shows but I can't select one". */
async function testBrowserReportsWhatTheEngineHolds() {
    console.log('the browser shows the result of a load on screen');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/kick.wav',
                         makeWav({ frames: 4410 }));

    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    ctx.host.tick();

    /* the mock engine reports back what the transfer declared */
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    ctx.host.tick();

    const screen = ctx.screen.map((x) => x.text).join(' ');
    check(/Loaded/.test(screen),
          `no confirmation on screen after a load; screen was "${screen}"`);
    check(/kick/.test(screen), `the loaded name is not shown; screen was "${screen}"`);
}

/* A failure has to say so, and must not claim success. */
async function testBrowserReportsFailure() {
    console.log('an unreadable file reports failure on screen');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/notes.wav',
                         Buffer.from('this is not a wav at all'));

    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    ctx.host.tick();

    const screen = ctx.screen.map((x) => x.text).join(' ');
    check(/Not a WAV|Could not read/.test(screen),
          `a bad file gave no error on screen; screen was "${screen}"`);
    check(!/Loaded/.test(screen), 'a failed load claimed success');
}

/* The engine is the authority. If the transfer is dropped in transit, the UI
 * must NOT report success just because it finished sending. */
async function testLoadTrustsTheEngineNotItself() {
    console.log('a transfer the engine did not take is reported as failed');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/a.wav',
                         makeWav({ frames: 1000 }));

    /* The engine refuses everything: sample_end commits nothing. This is the
     * transfer being dropped in transit, which the UI can only detect by
     * asking rather than assuming. */
    const realSet = ctx.host.host_module_set_param;
    ctx.host.host_module_set_param = (k, v) => {
        realSet(k, v);
        if (k === 'sample_end') { ctx.store.sample_frames = '0'; ctx.store.sample_name = ''; }
    };

    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    const ok = ctx.host.loadSampleFile('/data/UserData/UserLibrary/Samples/a.wav');
    check(ok === false, 'the UI reported success while the engine held nothing');
    ctx.host.tick();
    const screen = ctx.screen.map((x) => x.text).join(' ');
    check(/failed/i.test(screen), `no failure shown; screen was "${screen}"`);
}


/* Leaving the browser open after a successful load left every pad inert with
 * no sign why — reported from hardware as the machine palette not working,
 * when in fact the browser was still swallowing input. */
async function testLoadClosesTheBrowserAndPadsWorkAgain() {
    console.log('a successful load closes the browser and returns the pads');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/kick.wav',
                         makeWav({ frames: 4410 }));

    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    ctx.host.tick();

    const screen = ctx.screen.map((x) => x.text).join(' ');
    check(!/SAMPLES/.test(screen),
          `the browser stayed open after loading; screen was "${screen}"`);
    check(/Loaded/.test(screen),
          `the confirmation vanished with the browser; screen was "${screen}"`);

    /* and the palette works again — this is the reported symptom. One Shot is
     * a source, so it now sits at its position in the SRC family rather than
     * behind a Shift bank. */
    ctx.writes.length = 0;
    const oneShot = SRC_FAMILY.indexOf(21);
    ctx.host.onMidiMessageInternal(noteOn(PALETTE_ORDER[oneShot]));
    ctx.host.onMidiMessageInternal(noteOff(PALETTE_ORDER[oneShot]));
    const loaded = ctx.writes.find((w) => STAGE_KEY.indexOf(w.key) >= 0);
    check(loaded && parseInt(`${loaded.val}`, 10) === 21,
          `the One Shot palette pad loaded ${loaded && loaded.val}, expected 21 ` +
          `— the pads are still locked out`);
}

/* A FAILED load must keep the browser open: the next thing you want is
 * another file, not to be thrown back to the sequencer. */
async function testFailedLoadKeepsTheBrowserOpen() {
    console.log('a failed load leaves the browser open to try another file');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.dirs.add('/data/UserData/UserLibrary/Samples');
    ctx.vfs.binaries.set('/data/UserData/UserLibrary/Samples/bad.wav',
                         Buffer.from('not a wav'));

    holdShift(ctx, true);
    ctx.host.onMidiMessageInternal(noteOn(70));
    ctx.host.onMidiMessageInternal(noteOff(70));
    holdShift(ctx, false);
    ctx.host.onMidiMessageInternal(cc(JOG_CLICK, 127));
    ctx.host.tick();

    const screen = ctx.screen.map((x) => x.text).join(' ');
    check(/SAMPLES/.test(screen),
          `the browser closed on a failed load; screen was "${screen}"`);
}


/* Hardware, 2026-07-29: a sysex dump streamed through the MIDI_IN ring and
 * reached this handler as a burst of bytes reinterpreted as three-byte
 * messages — status 240, then 29, 58, 178, then 247 — after which the stream
 * degraded to an endless run of status=0 d1=0 d2=0. Thousands arrived. The
 * module ran without the house noise filter, so all of it was processed. */
async function testGarbageMidiIsIgnored() {
    console.log('sysex, clock and misaligned bytes never reach the surface');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.tick();
    const before = ctx.screen.map((x) => x.text).join(' ');
    ctx.writes.length = 0;

    /* the exact stream captured from the device */
    const garbage = [
        [178, 0, 77], [240, 0, 33], [29, 1, 1], [58, 0, 77], [0, 247, 0],
        [0xF8, 0, 0], [0xD0, 64, 0], [0xA0, 60, 100], [0x90, 3, 100]
    ];
    for (let i = 0; i < 200; i++) {
        for (const g of garbage) ctx.host.onMidiMessageInternal(g);
        ctx.host.onMidiMessageInternal([0, 0, 0]);
    }
    ctx.host.tick();

    check(ctx.writes.length === 0,
          `garbage MIDI wrote ${ctx.writes.length} parameters: ` +
          JSON.stringify(ctx.writes.slice(0, 4)));
    check(ctx.screen.map((x) => x.text).join(' ') === before,
          'garbage MIDI changed what is on screen');
}

/* ...and real input must still get through the new guard. */
async function testRealInputStillWorksThroughTheFilter() {
    console.log('real pad and knob input survives the noise filter');
    const ctx = await loadUI();
    ctx.host.init();
    await gotoGlobalPage(ctx);
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));
    check(ctx.writes.some((w) => w.key === STAGE_KEY[0]),
          'the filter swallowed a real knob turn');

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(PALETTE_ORDER[1]));
    ctx.host.onMidiMessageInternal(noteOff(PALETTE_ORDER[1]));
    check(ctx.writes.length > 0, 'the filter swallowed a real pad press');
}


/* Move's step buttons are NOTES 16-31. This handler lived in the CC branch,
 * so on hardware nothing reached it: the sequencer could not be played from
 * the surface at all, and the note fell through to the engine which fired the
 * sample. Every step check passed because the harness sent CCs too. */
async function testStepsArriveAsNotes() {
    console.log('step buttons work as notes, the way the hardware sends them');
    const ctx = await loadUI();
    ctx.host.init();

    /* the exact message the device logs: status=144 d1=20 d2=127 */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal([0x90, 20, 127]);
    ctx.host.onMidiMessageInternal([0x90, 20, 0]);
    const toggled = ctx.writes.find((w) => /^step\d+$/.test(w.key));
    check(!!toggled, `a step note toggled no trig; wrote ${JSON.stringify(ctx.writes)}`);
    check(toggled && toggled.key === 'step4',
          `note 20 toggled ${toggled && toggled.key}, expected step4 (20 - 16)`);

    /* and the p-lock gesture, which is the whole point of the module */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal([0x90, 16, 127]);      /* hold step 1 */
    ctx.host.onMidiMessageInternal(cc(KNOB1, 3));         /* turn a knob  */
    ctx.host.onMidiMessageInternal([0x90, 16, 0]);        /* release      */
    const locked = ctx.writes.find((w) => /^lock\d+_\d+$/.test(w.key));
    check(!!locked,
          `hold-step + knob wrote no lock; got ${JSON.stringify(ctx.writes)}`);
}


/* The launch gesture is itself a Shift combo (Shift+Vol+jog click), and
 * shadow_ui does not forward MIDI to a module until init() has returned —
 * measured at about six seconds. The release therefore lands inside that
 * window and is discarded, so a module that trusts its own CC 49 tracking
 * starts life believing Shift is held, forever.
 *
 * On hardware that did not look like one bug. It looked like several: knobs
 * edited base values instead of writing locks, palette pads loaded machine+21,
 * and the slot pad opened the sample browser. All reported separately. */
async function testShiftDoesNotLatchFromTheLaunchGesture() {
    console.log('a shift-on with no release does not latch the module');
    const ctx = await loadUI();
    ctx.host.init();

    /* the press arrives, the release never does */
    ctx.host.setShift(1);
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    for (let i = 0; i < 60; i++) ctx.host.tick();

    /* a knob must now write a LOCK, not edit the base — which is the whole
     * gesture the module exists for */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(stepDown(0));
    ctx.host.onMidiMessageInternal(cc(KNOB1, 4));
    ctx.host.onMidiMessageInternal(stepUp(0));
    const locked = ctx.writes.find((w) => /^lock\d+_\d+$/.test(w.key));
    check(!!locked,
          `Shift stayed latched from launch: hold-step + knob wrote ` +
          `${JSON.stringify(ctx.writes)} instead of a lock`);
}

/* ------------------------------------------------------------------ run */

const tests = [
    testInitReadsOnlyServedKeys,
    testShiftDoesNotLatchFromTheLaunchGesture,
    testStepsArriveAsNotes,
    testHoldStepPlusKnobLocks,
    testLastStageLocksAppendRatherThanCollide,
    testLockNudgeStartsFromLock,
    testPlainTapTogglesTrig,
    testShiftEscapesTheLockGesture,
    testMachinePaletteLoadsMachines,
    testPaletteRefusesOutOfFamilyPads,
    testTransportPads,
    testJogSetsLengthAndStepAttrs,
    testCopyPasteClear,
    testNoUnknownWritesAnywhere,
    testResumeForcesRepaints,
    testGarbageMidiIsIgnored,
    testRealInputStillWorksThroughTheFilter,
    testMachineColorTableCoversEveryMachine,
    testPaletteNeverShadowsTheFunctionPads,
    testEveryMachineIsReachableFromThePalette,
    testSampleScanFindsNestedFiles,
    testSampleScanIsBounded,
    testSampleBrowserIsReachableAndLoads,
    testBrowserReportsWhatTheEngineHolds,
    testLoadClosesTheBrowserAndPadsWorkAgain,
    testFailedLoadKeepsTheBrowserOpen,
    testBrowserReportsFailure,
    testLoadTrustsTheEngineNotItself,
    testSampleBrowserClosesTheWayItOpened,
    testWavLoadRoundTrip,
    testWavVariantsAndChunkParsing,
    testOversizedSampleIsTruncated,
    testSampleTransferIsChunked,
    testGarbageFileIsRejected,
    testKnobResponseCurve,
    testFetchAllUsesBulkReads,
    testBulkDecodeIsPositionallyCorrect,
    testFeedbackGuardArmsOnRisk,
    testGuardSilentForChainBuild,
    testMonitorManualOverride,
    testLiveRecordToggle,
    testProbabilityMode,
    testLfo3AndEnvelopePages,
    testVoiceFilterPageIsReachable,
    testReaddirContractIsFaithful,
    testPresetSaveThenList,
    testPresetRestoresItsSample,
    testPresetWithAMissingSampleIsSurvivable,
    testPresetLoadRestoresState,
    testPresetDelete,
    testPresetSurvivesRenameFailure,
    testPresetEmptyDirIsSafe
];

console.log('Overwork UI harness (mocked against the real engine contract)\n');
for (const t of tests) {
    try {
        await t();
    } catch (e) {
        failures++;
        console.log(`  FAIL  ${t.name} threw: ${e.message}`);
    }
}
console.log(`\n${checks} checks, ${failures} failed`);
process.exit(failures ? 1 : 0);
