/*
 * Overwork — UI harness.
 *
 * Loads src/ui_overtake.js in a sandbox with the host globals mocked, drives
 * real input sequences, and checks what the UI does with them.
 *
 * The mock's get_param answers come from build/contract.json, generated by
 * test/dump_contract.c FROM THE ENGINE ITSELF. That matters: a mock written
 * from the UI's assumptions encodes the same misunderstanding twice and stays
 * green while the feature is broken on hardware — which is exactly how Mono
 * shipped a preset browser that never listed a file. The harness also fails if
 * the UI reads a key the engine does not serve, or writes one it does not
 * accept, so contract drift is caught rather than silently tolerated.
 *
 * Run via `make test`.
 */
import fs from 'fs';
import vm from 'vm';
import path from 'path';
import { fileURLToPath } from 'url';

const here = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(here, '..');

const contract = JSON.parse(fs.readFileSync(path.join(root, 'build/contract.json'), 'utf8'));
const settable = new Set([...contract.settable, ...contract.commands]);

let checks = 0;
let failures = 0;
function check(cond, msg) {
    checks++;
    if (!cond) { failures++; console.log(`  FAIL  ${msg}`); }
}

/* ------------------------------------------------------------- the mock */

/* Keys the engine serves as families — the fixture holds concrete instances,
 * so a request for lock12_3 is legal if lock<N>_<P> is a served family. */
const FAMILIES = [
    /^step\d+$/, /^locks\d+$/, /^lock\d+_\d+$/, /^locklabel\d+$/, /^prob\d+$/, /^trigtype\d+$/, /^song_row\d+$/
];

function familyServed(key) {
    if (!FAMILIES.some((re) => re.test(key))) return false;
    /* the family is served if the fixture holds at least one of its members */
    const shape = key.replace(/\d+/g, '#');
    return Object.keys(contract.get).some((k) => k.replace(/\d+/g, '#') === shape);
}

/* A virtual filesystem implementing QuickJS's REAL contracts, copied from
 * schwung's own preset browser and the C source — never from the code under
 * test. The two that bite:
 *   os.readdir  -> [names, errno] TUPLE, and names includes "." and ".."
 *   os.rename / os.remove -> return 0 or -errno, and NEVER throw
 * Host file bindings are separate and DO return booleans. */
function makeVFS() {
    const files = new Map();
    const dirs = new Set();
    let renameFails = false;

    return {
        files, dirs,
        failRenames(v) { renameFails = v; },

        readdir(path) {
            if (!dirs.has(path)) return [[], 2];            /* ENOENT */
            const names = ['.', '..'];                       /* real listings carry these */
            for (const f of files.keys()) {
                if (f.startsWith(path + '/')) {
                    const rest = f.slice(path.length + 1);
                    if (!rest.includes('/')) names.push(rest);
                }
            }
            return [names, 0];
        },
        rename(a, b) {
            if (renameFails) return -1;
            if (!files.has(a)) return -2;
            files.set(b, files.get(a));
            files.delete(a);
            return 0;
        },
        remove(p) {
            if (!files.has(p)) return -2;
            files.delete(p);
            return 0;
        },
        mkdir(p) { dirs.add(p); return 0; }
    };
}

function makeHost() {
    const store = Object.assign({}, contract.get);
    const writes = [];
    const reads = [];
    const unknownReads = new Set();
    const unknownWrites = new Set();
    const leds = new Map();
    const screen = [];
    const roundTrips = [];   /* one entry per blocking read of the DSP */

    const vfs = makeVFS();

    const host = {
        __vfs: vfs,
        /* Host file bindings return booleans / string-or-null — a DIFFERENT
         * contract from the os.* calls above. */
        host_write_file(path, data) {
            const dir = path.slice(0, path.lastIndexOf('/'));
            if (!vfs.dirs.has(dir)) return false;
            vfs.files.set(path, String(data));
            return true;
        },
        host_read_file(path) {
            return vfs.files.has(path) ? vfs.files.get(path) : null;
        },
        host_ensure_dir(path) { vfs.dirs.add(path); return true; },

        /* Every one of these is a blocking round-trip on hardware, serviced
         * once per SPI frame. Counting them is the point — a UI that is
         * "correct" but takes sixty frames to redraw is broken on the Move. */
        host_module_get_param(key) {
            roundTrips.push({ bulk: false, keys: [key] });
            reads.push(key);
            if (key in store) return store[key];
            if (familyServed(key)) {
                /* a member the fixture did not capture: answer the way the
                 * engine does for an untouched step */
                if (/^lock\d+_\d+$/.test(key)) return '-1';
                if (/^step\d+$/.test(key)) return '0:0:0:0:0';
                if (/^locks\d+$/.test(key)) return '';
                if (/^locklabel\d+$/.test(key)) return '?';
            }
            unknownReads.add(key);
            return null;
        },
        /* BULK_GET, transcribed from shim_handle_param_bulk / bulk_next in
         * schwung's src/schwung_shim.c — NOT from the code under test. The
         * request is "<count>\n" then count records of "<len>\n<key>"; the
         * response is the same shape carrying values, and a key the DSP does
         * not answer comes back as a zero-length record rather than being
         * omitted. The shim refuses more than 64 items outright. */
        host_module_get_params(blob) {
            const s = `${blob}`;
            let p = 0;
            const readLen = () => {
                let n = 0, any = false;
                while (p < s.length && s[p] >= '0' && s[p] <= '9') {
                    n = n * 10 + (s.charCodeAt(p) - 48); p++; any = true;
                }
                if (!any || s[p] !== '\n') return -1;
                p++;
                return n;
            };
            const count = readLen();
            if (count < 0) return null;
            if (count > 64) return null;              /* SHADOW_BULK_MAX_ITEMS */
            const keys = [];
            for (let i = 0; i < count; i++) {
                const len = readLen();
                if (len < 0) return null;
                keys.push(s.slice(p, p + len));
                p += len;
            }
            roundTrips.push({ bulk: true, keys });
            let out = `${keys.length}\n`;
            for (const k of keys) {
                reads.push(k);
                let v = null;
                if (k in store) v = store[k];
                else if (familyServed(k)) {
                    if (/^lock\d+_\d+$/.test(k)) v = '-1';
                    else if (/^step\d+$/.test(k)) v = '0:0:0:0:0';
                    else if (/^locks\d+$/.test(k)) v = '';
                    else if (/^locklabel\d+$/.test(k)) v = '?';
                }
                if (v === null) { unknownReads.add(k); v = ''; }
                out += `${`${v}`.length}\n${v}`;
            }
            return out;
        },
        host_module_set_param(key, val) {
            writes.push({ key, val });
            const fam = key.replace(/\d+/g, '#');
            const known = settable.has(key)
                || [...settable].some((s) => s.replace(/\d+/g, '#') === fam);
            if (!known) unknownWrites.add(key);
            store[key] = `${val}`;
        },
        setLED(note, color) { leds.set(note, color); },
        setButtonLED(cc, color) { leds.set(`cc${cc}`, color); },
        clear_screen() { screen.length = 0; },
        print(x, y, text) { screen.push({ x, y, text }); },
        fill_rect() {},
        draw_rect() {},
        text_width(t) { return String(t).length * 5; },
        move_midi_internal_send() {},
        Date,
        Math,
        Number,
        JSON,
        String,
        Array,
        parseInt,
        parseFloat,
        isFinite,
        console
    };
    host.globalThis = host;
    return { host, vfs, writes, reads, roundTrips, unknownReads, unknownWrites, leds, screen, store };
}

/* Stub the three schwung shared modules the UI imports. */
const STUBS = {
    '/data/UserData/schwung/shared/constants.mjs': `
        export const MoveKnob1 = 71, MoveShift = 49, MoveMainButton = 3, MoveMainKnob = 14;
        export const Black=0, White=120, LightGrey=118, DarkGrey=124, Red=127, BrightRed=1;
        export const Blue=125, Green=126, BrightGreen=8, Cyan=14, Purple=22, SkyBlue=47;
        export const Lime=31, OrangeRed=2, BurntOrange=28, YellowGreen=30, TealGreen=12, Rose=24;
    `,
    '/data/UserData/schwung/shared/input_filter.mjs': `
        export function decodeDelta(v){ if(v===0) return 0; if(v>=1&&v<=63) return v; if(v>=65&&v<=127) return -(128-v); return 0; }
        export function setLED(n,c,f){ globalThis.setLED(n,c,f); }
        export function setButtonLED(n,c,f){ globalThis.setButtonLED(n,c,f); }
    `,
    '/data/UserData/schwung/shared/screen_reader.mjs': `
        export function announce(){}
        export function announceParameter(){}
        export function announceView(){}
    `,
    'os': `
        export function readdir(p){ return globalThis.__vfs.readdir(p); }
        export function rename(a,b){ return globalThis.__vfs.rename(a,b); }
        export function remove(p){ return globalThis.__vfs.remove(p); }
        export function mkdir(p){ return globalThis.__vfs.mkdir(p); }
    `
};

async function loadUI() {
    const ctx = makeHost();
    const context = vm.createContext(ctx.host);
    const src = fs.readFileSync(path.join(root, 'src/ui_overtake.js'), 'utf8');

    const mod = new vm.SourceTextModule(src, { context, identifier: 'ui_overtake.js' });
    await mod.link(async (spec) => {
        const code = STUBS[spec];
        if (!code) throw new Error(`unexpected import: ${spec}`);
        const m = new vm.SourceTextModule(code, { context, identifier: spec });
        await m.link(() => { throw new Error('nested import'); });
        return m;
    });
    await mod.evaluate();
    return ctx;
}

/* MIDI helpers matching what the shim delivers */
const cc   = (num, val) => [0xB0, num, val];
const noteOn  = (n) => [0x90, n, 127];
const noteOff = (n) => [0x80, n, 0];

const KNOB1 = 71, JOG = 14, SHIFT = 49, STEP1 = 16;

/* --------------------------------------------------------------- tests */

async function testInitReadsOnlyServedKeys() {
    console.log('init reads only keys the engine serves');
    const ctx = await loadUI();
    ctx.host.init();
    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
    check(ctx.reads.includes('machines'), 'UI never asked for the machine list');
    check(ctx.reads.includes('labels1'), 'UI never asked for slot 1 knob labels');
    check(ctx.screen.length > 0, 'init drew nothing to the screen');
    check(ctx.leds.size > 20, `init painted only ${ctx.leds.size} LEDs`);
}

/* The headline gesture. Holding a step and turning a knob must write a
 * lock<step>_<param> key — not the base parameter. */
async function testHoldStepPlusKnobLocks() {
    console.log('hold a step + turn a knob writes a parameter lock');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(cc(STEP1 + 2, 127));   /* hold step 3 */
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));         /* knob 1, +1  */

    const lockWrites = ctx.writes.filter((w) => /^lock\d+_\d+$/.test(w.key));
    check(lockWrites.length === 1,
          `expected one lock write, got ${JSON.stringify(ctx.writes)}`);
    if (lockWrites.length) {
        check(lockWrites[0].key === 'lock2_0',
              `expected lock2_0 (step 3, slot 1 knob A), got ${lockWrites[0].key}`);
    }
    const baseWrites = ctx.writes.filter((w) => /^fx\d_p\d$/.test(w.key));
    check(baseWrites.length === 0,
          `the base parameter must not move while locking, got ${JSON.stringify(baseWrites)}`);

    /* releasing after a lock must NOT also toggle the trig off */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(STEP1 + 2, 0));
    const stepWrites = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(stepWrites.length === 0,
          `release after locking should not rewrite the step, got ${JSON.stringify(stepWrites)}`);
}

/* Nudging an existing lock must start from the LOCK's value, not the base —
 * this is what the missing lock<N>_<P> getter used to break. */
async function testLockNudgeStartsFromLock() {
    console.log('nudging an existing lock continues from the locked value');
    const ctx = await loadUI();
    ctx.host.init();

    /* step 4 (index 3) has lock 0 = 100 in the fixture; base fx1_p1 is 76 */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(STEP1 + 3, 127));
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));

    const w = ctx.writes.find((x) => x.key === 'lock3_0');
    check(!!w, 'no write to lock3_0');
    if (w) {
        check(`${w.val}` === '101',
              `expected 101 (locked 100 + 1), got ${w.val} — the UI fell back to the base value`);
    }
}

async function testPlainTapTogglesTrig() {
    console.log('tapping a step with no edit toggles its trig');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(cc(STEP1 + 5, 127));
    ctx.host.onMidiMessageInternal(cc(STEP1 + 5, 0));

    const stepWrites = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(stepWrites.length === 1, `expected one step write, got ${stepWrites.length}`);
    if (stepWrites.length) {
        check(stepWrites[0].key === 'step5', `expected step5, got ${stepWrites[0].key}`);
        check(/^1:/.test(stepWrites[0].val),
              `empty step should turn on, got ${stepWrites[0].val}`);
    }
}

async function testShiftEscapesTheLockGesture() {
    console.log('shift + knob edits the base value even while a step is held');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(cc(STEP1 + 2, 127));
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));

    const lockWrites = ctx.writes.filter((w) => /^lock\d+_\d+$/.test(w.key));
    const baseWrites = ctx.writes.filter((w) => /^fx\d_p\d$/.test(w.key));
    check(lockWrites.length === 0, 'shift + knob must not create a lock');
    check(baseWrites.length === 1,
          `shift + knob should edit the base, got ${JSON.stringify(ctx.writes)}`);
}

async function testMachinePaletteLoadsMachines() {
    console.log('palette pads load machines into the focused slot');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(noteOn(92));           /* palette index 0 */
    ctx.host.onMidiMessageInternal(noteOff(92));
    let w = ctx.writes.find((x) => x.key === 'machine1');
    check(!!w && `${w.val}` === '0', `pad 92 should load machine 0 into FX1, got ${w && w.val}`);

    /* focus the other slot, then load again */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(70));           /* PAD_SLOT */
    ctx.host.onMidiMessageInternal(noteOff(70));
    ctx.host.onMidiMessageInternal(noteOn(99));           /* palette index 7 */
    ctx.host.onMidiMessageInternal(noteOff(99));
    w = ctx.writes.find((x) => x.key === 'machine2');
    check(!!w && `${w.val}` === '7', `pad 99 should load machine 7 into FX2, got ${w && w.val}`);
}

async function testTransportPads() {
    console.log('transport pads drive the sequencer');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(noteOn(68));           /* PLAY toggles */
    ctx.host.onMidiMessageInternal(noteOff(68));
    check(ctx.writes.some((w) => w.key === 'seq_on'), 'play pad did not write seq_on');

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(69));           /* FILL */
    ctx.host.onMidiMessageInternal(noteOff(69));
    check(ctx.writes.some((w) => w.key === 'fill'), 'fill pad did not write fill');
}

async function testJogSetsLengthAndStepAttrs() {
    console.log('jog sets pattern length, or the held step attribute in a mode');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;

    ctx.host.onMidiMessageInternal(cc(JOG, 1));           /* free jog */
    check(ctx.writes.some((w) => w.key === 'seq_len'),
          `free jog should set length, got ${JSON.stringify(ctx.writes)}`);

    /* condition mode, then hold a step and jog */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));      /* shift + pad 72 = COND */
    ctx.host.onMidiMessageInternal(noteOn(72));
    ctx.host.onMidiMessageInternal(noteOff(72));
    ctx.host.onMidiMessageInternal(cc(SHIFT, 0));
    ctx.host.onMidiMessageInternal(cc(STEP1 + 1, 127));
    ctx.host.onMidiMessageInternal(cc(JOG, 1));

    const stepWrite = ctx.writes.find((w) => w.key === 'step1');
    check(!!stepWrite, 'jog in condition mode did not write the step');
    if (stepWrite) {
        const cond = parseInt(`${stepWrite.val}`.split(':')[1], 10);
        check(cond === 1, `expected condition to advance to 1, got ${cond}`);
    }
}

async function testCopyPasteClear() {
    console.log('copy, paste and clear act on the visible page');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.host.onMidiMessageInternal(noteOn(73));           /* COPY  */
    ctx.host.onMidiMessageInternal(noteOff(73));
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(74));           /* PASTE */
    ctx.host.onMidiMessageInternal(noteOff(74));
    const pasted = ctx.writes.filter((w) => /^step\d+$/.test(w.key));
    check(pasted.length === 16, `paste should write 16 steps, wrote ${pasted.length}`);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(75));           /* CLEAR, short tap */
    ctx.host.onMidiMessageInternal(noteOff(75));
    const cleared = ctx.writes.filter((w) => /^step\d+$/.test(w.key) && `${w.val}` === '0:0:0:0');
    check(cleared.length === 16, `page clear should blank 16 steps, blanked ${cleared.length}`);
}

async function testNoUnknownWritesAnywhere() {
    console.log('every key the UI writes is one the engine accepts');
    const ctx = await loadUI();
    ctx.host.init();

    /* exercise a broad slice of the surface */
    for (const pad of [68, 69, 70, 71, 72, 73, 74, 80, 81, 82, 83, 92, 95, 99]) {
        ctx.host.onMidiMessageInternal(noteOn(pad));
        ctx.host.onMidiMessageInternal(noteOff(pad));
    }
    for (let s = 0; s < 16; s++) {
        ctx.host.onMidiMessageInternal(cc(STEP1 + s, 127));
        ctx.host.onMidiMessageInternal(cc(KNOB1 + (s % 8), 1));
        ctx.host.onMidiMessageInternal(cc(JOG, 1));
        ctx.host.onMidiMessageInternal(cc(STEP1 + s, 0));
    }
    for (let i = 0; i < 40; i++) ctx.host.tick();

    check(ctx.unknownWrites.size === 0,
          `UI wrote keys the engine does not accept: ${[...ctx.unknownWrites].join(', ')}`);
    check(ctx.unknownReads.size === 0,
          `UI read keys the engine does not serve: ${[...ctx.unknownReads].join(', ')}`);
}

/* A suspended overtake session resumes with its LEDs cleared; one paintAll is
 * ~60 writes in a tick and the shim's queue drops some. Overwork must force
 * several spaced repaints (the Smack v0.9.1 fix). */
async function testResumeForcesRepaints() {
    console.log('resume forces repeated full LED repaints');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.leds.clear();
    ctx.host.onResume();
    check(ctx.leds.size > 20, `onResume painted only ${ctx.leds.size} LEDs`);

    let repaints = 0;
    for (let i = 0; i < 40; i++) {
        ctx.leds.clear();
        ctx.host.tick();
        if (ctx.leds.size > 20) repaints++;
    }
    check(repaints >= 3, `expected at least 3 forced repaints after resume, saw ${repaints}`);
}

/* --------------------------------------------------------- v0.3.0 gestures */

async function testLiveRecordToggle() {
    console.log('shift + play arms live record');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    ctx.host.onMidiMessageInternal(noteOn(68));
    ctx.host.onMidiMessageInternal(noteOff(68));
    ctx.host.onMidiMessageInternal(cc(SHIFT, 0));
    const w = ctx.writes.find((x) => x.key === 'live_rec');
    check(!!w && `${w.val}` === '1', `shift+play did not arm live_rec (${w && w.val})`);
    /* unshifted play must still be play, not record */
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(68));
    ctx.host.onMidiMessageInternal(noteOff(68));
    check(ctx.writes.some((x) => x.key === 'seq_on'), 'plain play stopped writing seq_on');
}

async function testProbabilityMode() {
    console.log('shift + pattern-page selects probability mode, jog sets it');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    ctx.host.onMidiMessageInternal(noteOn(71));
    ctx.host.onMidiMessageInternal(noteOff(71));
    ctx.host.onMidiMessageInternal(cc(SHIFT, 0));

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(STEP1 + 4, 127));   /* hold step 5 */
    ctx.host.onMidiMessageInternal(cc(JOG, 127));          /* jog down    */
    const w = ctx.writes.find((x) => x.key === 'prob4');
    check(!!w, `jog in probability mode did not write prob4; got ${JSON.stringify(ctx.writes)}`);
    if (w) check(parseInt(`${w.val}`, 10) < 100,
                 `probability should have come down from 100, got ${w.val}`);
}

async function testLfo3AndEnvelopePages() {
    console.log('the edit pages reach LFO 3 and the modulation envelope');
    const ctx = await loadUI();
    ctx.host.init();
    const seen = new Set();
    for (let i = 0; i < 8; i++) {                 /* cycle every edit page */
        ctx.writes.length = 0;
        for (let k = 0; k < 8; k++) ctx.host.onMidiMessageInternal(cc(KNOB1 + k, 1));
        ctx.writes.forEach((x) => seen.add(x.key.replace(/\d+$/, '')));
        ctx.host.onMidiMessageInternal(noteOn(72));
        ctx.host.onMidiMessageInternal(noteOff(72));
    }
    check([...seen].some((k) => k.startsWith('lfo3_')),
          `no LFO 3 parameter was reachable; saw ${[...seen].join(', ')}`);
    check([...seen].some((k) => k.startsWith('menv_')),
          `no envelope parameter was reachable; saw ${[...seen].join(', ')}`);
}

/* Knob response has now been wrong in BOTH directions on hardware, so this
 * pins the exact numbers rather than a range.
 *
 * decodeDelta returns ACCUMULATED movement — up to 63 from one event. Applied
 * raw to the 21-entry machine select it hit an end stop every time ("fx 2 only
 * does warble or bypass"); clamped to one step per event, crossing the list
 * took twenty separate clicks ("super slow"). The rule is a cap of a quarter
 * of the range: one detent moves one, a full-speed spin moves ceil(span/4). */
async function gotoGlobalPage(ctx) {
    /* Edit pages cycle FX, LFO1, LFO2, LFO3, MOD ENV, GLOBAL — the machine
     * selects live on GLOBAL, five presses of the edit-page pad away. */
    for (let i = 0; i < 5; i++) {
        ctx.host.onMidiMessageInternal(noteOn(72));
        ctx.host.onMidiMessageInternal(noteOff(72));
    }
    ctx.host.tick();
}

/* Start the UI with a chosen value already in the DSP, on the GLOBAL page.
 * The value has to be in the store BEFORE init — the UI mirrors the DSP at
 * load, and deliberately does not re-read on every knob event. */
async function atGlobalWith(seed) {
    const ctx = await loadUI();
    Object.assign(ctx.store, seed);
    ctx.host.init();
    await gotoGlobalPage(ctx);
    ctx.writes.length = 0;
    return ctx;
}

async function testKnobResponseCurve() {
    console.log('knob response: one detent moves one, a fast spin moves a quarter of the range');

    const nMachines = JSON.parse(
        fs.readFileSync(path.join(root, 'build/contract.json'), 'utf8')
    ).get.machines.split(',').length;                 /* 21, from the engine */
    const cap = Math.ceil((nMachines - 1) / 4);

    let ctx = await atGlobalWith({ machine1: '5' });
    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));     /* one detent */
    let w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 6,
          `one detent moved machine1 to ${w && w.val} — expected 6`);

    ctx = await atGlobalWith({ machine1: '5' });
    ctx.host.onMidiMessageInternal(cc(KNOB1, 25));    /* a full-speed spin */
    w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 5 + cap,
          `a 25-detent event moved machine1 to ${w && w.val} — expected ${5 + cap}: ` +
          `neither an end stop nor a single step`);

    /* the top of the list must be REACHABLE — Grainer was excluded when this
     * range was a hardcoded constant */
    ctx = await atGlobalWith({ machine1: `${nMachines - 2}` });
    ctx.host.onMidiMessageInternal(cc(KNOB1, 40));
    w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === nMachines - 1,
          `could not reach the last machine (${nMachines - 1}); got ${w && w.val}`);

    /* wide ranges keep the acceleration, or 0-127 becomes unusable */
    ctx = await atGlobalWith({ mix: '40' });
    ctx.host.onMidiMessageInternal(cc(KNOB1 + 2, 20));   /* MIX, 0-127 */
    const m = ctx.writes.find((x) => x.key === 'mix');
    check(m && parseInt(`${m.val}`, 10) === 60,
          `wide-range acceleration was lost: mix went to ${m && m.val}, expected 60`);
}

/* Every read is a blocking round-trip to the shim serviced once per SPI frame.
 * fetchAll wants ~58 keys; one at a time that is over a second of stall, and it
 * runs from the machine-select handler. It must use the bulk path. */
async function testFetchAllUsesBulkReads() {
    console.log('a full refresh costs a couple of round-trips, not sixty');
    const ctx = await loadUI();
    ctx.host.init();

    ctx.roundTrips.length = 0;
    ctx.host.onMidiMessageInternal(noteOn(76));      /* palette: load a machine */
    ctx.host.onMidiMessageInternal(noteOff(76));

    check(ctx.roundTrips.length > 0, 'loading a machine refreshed nothing');
    check(ctx.roundTrips.length <= 4,
          `a machine change cost ${ctx.roundTrips.length} round-trips — at ~23 ms ` +
          `each that is the "super slow" stall; batch them with get_params`);
    const bulk = ctx.roundTrips.filter((r) => r.bulk).length;
    check(bulk > 0, 'the bulk get_params path was never used');
}

/* The bulk wire format is schwung's, not ours: "<count>\n" then count records
 * of "<len>\n<bytes>". Decode it wrong and every value shifts by one key —
 * which would look like working software right up until a knob edits the wrong
 * parameter. The mock implements the format from the shim's own parser; this
 * proves the UI reads real values back out of it, by nudging a value it could
 * only have got from a bulk response.
 *
 * `machines` is variable-length and sits in the same batch, so a naive decoder
 * that assumed fixed records would land somewhere else entirely. */
async function testBulkDecodeIsPositionallyCorrect() {
    console.log('bulk-read values land on the right keys');
    const ctx = await atGlobalWith({ machine1: '13', mix: '99' });

    ctx.host.onMidiMessageInternal(cc(KNOB1, 1));           /* machine1 +1 */
    const w = ctx.writes.find((x) => x.key === 'machine1');
    check(w && parseInt(`${w.val}`, 10) === 14,
          `machine1 continued from the wrong base: wrote ${w && w.val}, expected 14`);

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(KNOB1 + 2, 1));       /* mix +1 */
    const m = ctx.writes.find((x) => x.key === 'mix');
    check(m && parseInt(`${m.val}`, 10) === 100,
          `mix continued from the wrong base: wrote ${m && m.val}, expected 100`);
}

/* -------------------------------------------------------- feedback guard */

function withJack(ctx, speakers, lineIn) {
    ctx.host.host_speaker_active = () => speakers;
    ctx.host.host_line_in_connected = () => lineIn;
}

async function testFeedbackGuardArmsOnRisk() {
    console.log('the feedback guard mutes the input when the mic can hear the speakers');
    const ctx = await loadUI();
    ctx.store.hw_input = '1';
    withJack(ctx, true, true);            /* speakers on, but a cable is in */
    ctx.host.init();
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor' && `${w.val}` === '0'),
          'guard muted with a cable plugged in — that is not a feedback path');

    /* pull the cable: speakers live, mic open */
    withJack(ctx, true, false);
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    const muted = ctx.writes.find((w) => w.key === 'monitor');
    check(!!muted && `${muted.val}` === '0',
          `guard did not mute on risk; writes were ${JSON.stringify(ctx.writes)}`);

    /* plug back in: it must restore, not stay muted forever */
    withJack(ctx, true, true);
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    const restored = ctx.writes.find((w) => w.key === 'monitor');
    check(!!restored && `${restored.val}` === '1',
          `guard did not restore the input when the risk cleared (${restored && restored.val})`);
}

async function testGuardSilentForChainBuild() {
    console.log('the guard stays out of the way when the build does not read the mic');
    const ctx = await loadUI();
    ctx.store.hw_input = '0';             /* the audio_fx build */
    withJack(ctx, true, false);           /* would be risky IF it read the mic */
    ctx.host.init();
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor'),
          'the guard armed for a build that processes upstream chain audio');
}

async function testMonitorManualOverride() {
    console.log('shift + fill overrides the guard');
    const ctx = await loadUI();
    ctx.store.hw_input = '1';
    withJack(ctx, true, false);
    ctx.host.init();
    for (let i = 0; i < 30; i++) ctx.host.tick();

    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    ctx.host.onMidiMessageInternal(noteOn(69));
    ctx.host.onMidiMessageInternal(noteOff(69));
    ctx.host.onMidiMessageInternal(cc(SHIFT, 0));
    const on = ctx.writes.find((w) => w.key === 'monitor');
    check(!!on && `${on.val}` === '1', `override did not unmute (${on && on.val})`);

    /* and the guard must not immediately stamp on the override */
    ctx.writes.length = 0;
    for (let i = 0; i < 30; i++) ctx.host.tick();
    check(!ctx.writes.some((w) => w.key === 'monitor' && `${w.val}` === '0'),
          'the guard overrode the user while the risk state was unchanged');
}

/* ---------------------------------------------------------------- presets */

const PDIR = '/data/UserData/schwung/presets/overwork';

/* Open the preset browser: Shift + jog click. */
function openPresets(ctx) {
    ctx.host.onMidiMessageInternal(cc(SHIFT, 127));
    ctx.host.onMidiMessageInternal(cc(3, 127));      /* MoveMainButton */
    ctx.host.onMidiMessageInternal(cc(SHIFT, 0));
    ctx.host.tick();                                 /* the device redraws on tick */
}

/* THE guard on the whole approach. If the mock's os.readdir were written from
 * the UI's assumptions — a flat array of filenames — this test would pass
 * against a broken implementation. So assert the mock reproduces the REAL
 * contract, and that the naive reading of it fails the way Mono did. */
async function testReaddirContractIsFaithful() {
    console.log('the os.readdir mock reproduces the real tuple contract');
    const ctx = await loadUI();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/one.json`, '{"name":"One","state":"{}"}');

    const raw = ctx.vfs.readdir(PDIR);
    check(Array.isArray(raw) && Array.isArray(raw[0]),
          'readdir must answer a [names, errno] tuple, got ' + JSON.stringify(raw));
    check(raw[0].includes('.') && raw[0].includes('..'),
          'a real listing includes "." and ".."; mock gave ' + JSON.stringify(raw[0]));
    check(raw[1] === 0, 'errno slot should be 0 on success, got ' + raw[1]);

    /* the naive implementation Mono shipped, run against this same mock */
    const naive = (() => {
        const names = ctx.vfs.readdir(PDIR);      /* treated as a flat array */
        try { return /\.json$/i.test(names) ? [String(names).replace(/\.json$/i, '')] : []; }
        catch (e) { return ['THREW']; }
    })();
    check(naive.length === 0 || naive[0] === 'THREW',
          'the naive flat-array reading should find nothing (or throw) against the ' +
          'real contract — it "found" ' + JSON.stringify(naive) +
          ', so the mock is too forgiving to catch the Mono bug');

    /* os.rename and os.remove must report failure by return code, not throw */
    ctx.vfs.failRenames(true);
    let threw = false;
    let rc = 0;
    try { rc = ctx.vfs.rename(`${PDIR}/one.json`, `${PDIR}/two.json`); }
    catch (e) { threw = true; }
    check(!threw && rc < 0, 'a failing rename must return -errno, not throw');
    ctx.vfs.failRenames(false);
    check(ctx.vfs.remove(`${PDIR}/nope.json`) < 0, 'removing a missing file must return -errno');
}

async function testPresetSaveThenList() {
    console.log('saving a preset writes a file the browser can then list');
    const ctx = await loadUI();
    ctx.host.init();

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* click on "Save new" */

    const written = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.json'));
    check(written.length === 1, `expected one preset file, got ${JSON.stringify(written)}`);
    check(!written.some((f) => f.endsWith('.tmp')), 'a .tmp file was left behind');

    const payload = JSON.parse(ctx.vfs.files.get(written[0]));
    check(!!payload.state, 'preset carries no state blob');
    check(payload.module === 'overwork', `preset module tag is ${payload.module}`);

    /* the saved preset must now appear in the list — the exact step that
     * silently did nothing in Mono */
    ctx.host.tick();
    const shown = ctx.screen.map((l) => l.text).join(' ');
    check(/Pattern 1/.test(shown),
          `saved preset does not appear in the browser; screen shows: ${shown}`);
}

async function testPresetLoadRestoresState() {
    console.log('loading a preset pushes its state back to the engine');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/saved.json`,
        JSON.stringify({ v: 1, name: 'Saved', module: 'overwork',
                         state: '{"v":1,"mix":42,"m1":5,"p1":[1,2,3,4,5,6,7,8]}' }));

    openPresets(ctx);
    ctx.writes.length = 0;
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* click loads index 1 */

    const w = ctx.writes.find((x) => x.key === 'state');
    check(!!w, `no state write on load; writes were ${JSON.stringify(ctx.writes.slice(0,4))}`);
    if (w) check(/"mix":42/.test(`${w.val}`), `state pushed was ${w.val}`);
}

async function testPresetDelete() {
    console.log('the clear pad deletes the selected preset');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.host.host_ensure_dir(PDIR);
    ctx.host.host_write_file(`${PDIR}/gone.json`, '{"name":"Gone","state":"{}"}');

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(noteOn(75));       /* PAD_CLEAR */
    ctx.host.onMidiMessageInternal(noteOff(75));
    check(!ctx.vfs.files.has(`${PDIR}/gone.json`), 'preset file survived delete');
}

/* If the rename step fails, the payload must still reach its destination
 * rather than being stranded in the .tmp file. */
async function testPresetSurvivesRenameFailure() {
    console.log('a refused rename still saves the preset');
    const ctx = await loadUI();
    ctx.host.init();
    ctx.vfs.failRenames(true);

    openPresets(ctx);
    ctx.host.onMidiMessageInternal(cc(3, 127));       /* Save new */

    const finals = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.json'));
    const temps = [...ctx.vfs.files.keys()].filter((f) => f.endsWith('.tmp'));
    check(finals.length === 1, `preset not saved when rename failed: ${JSON.stringify([...ctx.vfs.files.keys()])}`);
    check(temps.length === 0, 'a .tmp file was stranded after the rename failure');
}

/* An empty or missing directory must give an empty list, never an exception —
 * a throw here is fatal to the whole overtake session. */
async function testPresetEmptyDirIsSafe() {
    console.log('an empty or missing preset directory does not throw');
    const ctx = await loadUI();
    ctx.host.init();
    let threw = false;
    try {
        openPresets(ctx);                             /* dir does not exist yet */
        for (let i = 0; i < 5; i++) ctx.host.tick();
        ctx.host.host_ensure_dir(PDIR);               /* now exists but is empty */
        openPresets(ctx);
        for (let i = 0; i < 5; i++) ctx.host.tick();
    } catch (e) { threw = true; }
    check(!threw, 'the preset browser threw on an empty directory');

    /* a corrupt preset must not take the browser down either */
    ctx.host.host_write_file(`${PDIR}/bad.json`, 'not json at all');
    threw = false;
    try { openPresets(ctx); for (let i = 0; i < 5; i++) ctx.host.tick(); }
    catch (e) { threw = true; }
    check(!threw, 'a corrupt preset file threw');
}

/* ------------------------------------------------------------------ run */

const tests = [
    testInitReadsOnlyServedKeys,
    testHoldStepPlusKnobLocks,
    testLockNudgeStartsFromLock,
    testPlainTapTogglesTrig,
    testShiftEscapesTheLockGesture,
    testMachinePaletteLoadsMachines,
    testTransportPads,
    testJogSetsLengthAndStepAttrs,
    testCopyPasteClear,
    testNoUnknownWritesAnywhere,
    testResumeForcesRepaints,
    testKnobResponseCurve,
    testFetchAllUsesBulkReads,
    testBulkDecodeIsPositionallyCorrect,
    testFeedbackGuardArmsOnRisk,
    testGuardSilentForChainBuild,
    testMonitorManualOverride,
    testLiveRecordToggle,
    testProbabilityMode,
    testLfo3AndEnvelopePages,
    testReaddirContractIsFaithful,
    testPresetSaveThenList,
    testPresetLoadRestoresState,
    testPresetDelete,
    testPresetSurvivesRenameFailure,
    testPresetEmptyDirIsSafe
];

console.log('Overwork UI harness (mocked against the real engine contract)\n');
for (const t of tests) {
    try {
        await t();
    } catch (e) {
        failures++;
        console.log(`  FAIL  ${t.name} threw: ${e.message}`);
    }
}
console.log(`\n${checks} checks, ${failures} failed`);
process.exit(failures ? 1 : 0);
